### ISSUE TITLE
Single Scan: Scan errors are not handled

### ISSUE THREAD

**Issue by jflesch** [jflesch/paperwork#278]
```
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/paperwork/frontend/util/actions.py", line 58, in on_button_clicked_cb
  File "build/bdist.linux-x86_64/egg/paperwork/frontend/util/actions.py", line 55, in __do
  File "build/bdist.linux-x86_64/egg/paperwork/frontend/mainwindow/__init__.py", line 1479, in do
    
  File "/usr/lib/python2.7/site-packages/pyinsane-1.3.3_git-py2.7.egg/pyinsane/abstract_th.py", line 237, in scan
    return ScanSession(self, multiple)
  File "/usr/lib/python2.7/site-packages/pyinsane-1.3.3_git-py2.7.egg/pyinsane/abstract_th.py", line 171, in __init__
    self._session = SaneAction(scanner._abstract_dev.scan, multiple=multiple).wait()
  File "/usr/lib/python2.7/site-packages/pyinsane-1.3.3_git-py2.7.egg/pyinsane/abstract_th.py", line 58, in wait
    raise self.exception
StopIteration
```

Occurred on:
```
        scan_session = dev.scan(multiple=False)
```

**Comment by jflesch** [comment]
cac7ad16bc514d7410130d6922a483333df89358
