### ISSUE TITLE
Problem with cairo.Context on Ubuntu 13.10

### ISSUE THREAD

**Issue by tiramiseb** [jflesch/paperwork#283]
Hello,

After months without using Paperwork, I have reinstalled it, on Ubuntu 13.10.
I have installed all dependencies as Ubuntu packages (except, of course, pyocr and pyinsane), then I have installed with pip (sudo pip install paperwork).

The thumbnails are not displayed and I get the following on the console:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gi/overrides/GLib.py", line 634, in <lambda>
    return (lambda data: callback(*data), user_data)
  File "/usr/local/lib/python2.7/dist-packages/paperwork/frontend/mainwindow.py", line 3272, in set_progression
    self.status['text'].pop(context_id)
TypeError: Couldn't find conversion for foreign struct 'cairo.Context'
/usr/local/lib/python2.7/dist-packages/paperwork/paperwork.py:105: Warning: unable to set property 'editable' of type 'gboolean' from value of type 'gchararray'
  Gtk.main()
```

There is also the following, twice:
```
*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug
```

And the following is probably also related to cairo:
```
ERROR  paperwork.frontend.jobs        ===> Job DocThumbnailer:0 raised an exception: <type 'exceptions.KeyError'>: 'could not find foreign type Context'
ERROR  paperwork.frontend.jobs         0: /usr/local/lib/python2.7/dist-packages/paperwork/frontend/jobs.py: L  158: _run
ERROR  paperwork.frontend.jobs         1: /usr/local/lib/python2.7/dist-packages/paperwork/frontend/mainwindow.py: L  642: do
ERROR  paperwork.frontend.jobs         2: /usr/local/lib/python2.7/dist-packages/paperwork/backend/common/page.py: L  127: get_thumbnail
ERROR  paperwork.frontend.jobs         3: /usr/local/lib/python2.7/dist-packages/paperwork/backend/pdf/page.py: L  182: _get_thumbnail
ERROR  paperwork.frontend.jobs         4: /usr/local/lib/python2.7/dist-packages/paperwork/backend/pdf/page.py: L  172: __render_img
ERROR  paperwork.frontend.jobs        ---> Job DocThumbnailer:0 was started by:
ERROR  paperwork.frontend.jobs         0: /usr/local/bin/paperwork: L    6: <module>
ERROR  paperwork.frontend.jobs         1: /usr/local/lib/python2.7/dist-packages/paperwork/paperwork.py: L  105: main
ERROR  paperwork.frontend.jobs         2: /usr/local/lib/python2.7/dist-packages/paperwork/frontend/mainwindow.py: L 4104: __on_doc_lines_shown
ERROR  paperwork.frontend.jobs         3: /usr/local/lib/python2.7/dist-packages/paperwork/frontend/jobs.py: L  227: schedule
```

I have never worked with cairo and I don't know where I can dig in order to debug this...

**Comment by jflesch** [comment]
Done: c2ee84afd7b054a46cec93f32016177f2c608253
This is one ugly way to find if the package is missing .....

**Comment by jflesch** [comment]
For those looking at this ticket when trying to install Paperwork >= 1.0:
Paperwork has switched to Python 3, so now, the missing package you're looking to install is ```python3-gi-cairo``` (and not ```python-gi-cairo```).
