### ISSUE TITLE
Fail to start: unexpected keyword argument 'spelling'

### ISSUE THREAD

**Issue by mathieumd** [jflesch/paperwork#372]
Paperwork worked until today's `sudo pip install --upgrade paperwork`. But now, it cannot even start:

```
paperwork

Traceback (most recent call last):
  File "/usr/local/bin/paperwork", line 3, in <module>
    from paperwork.paperwork import main
  File "/usr/local/lib/python2.7/dist-packages/paperwork/paperwork.py", line 31, in <module>
    from frontend.mainwindow import ActionRefreshIndex, MainWindow
  File "/usr/local/lib/python2.7/dist-packages/paperwork/frontend/mainwindow/__init__.py", line 63, in <module>
    from paperwork.backend.docsearch import DocSearch
  File "/usr/local/lib/python2.7/dist-packages/paperwork/backend/docsearch.py", line 301, in <module>
    class DocSearch(object):
  File "/usr/local/lib/python2.7/dist-packages/paperwork/backend/docsearch.py", line 322, in DocSearch
    spelling=True, scorable=True),
TypeError: __init__() got an unexpected keyword argument 'spelling'
```

```
find /usr/local/lib/python2.7 -name "*paperwork*"

/usr/local/lib/python2.7/dist-packages/paperwork-0.2.3-py2.7.egg-info
/usr/local/lib/python2.7/dist-packages/paperwork
/usr/local/lib/python2.7/dist-packages/paperwork/paperwork.py
/usr/local/lib/python2.7/dist-packages/paperwork/paperwork.pyc
```

**Comment by jflesch** [comment]
Do you know from which version you upgraded ?

Also, what is the output of 'pip show Whoosh' ?

**Comment by mathieumd** [comment]
I don't know from what version I upgraded. Is there still a way to know it?

All I can say is that the last time I upgaded was on February 18, 2015, 12:30 CET (thanks Bash history :)).

```
pip show Whoosh

---
Name: Whoosh
Version: 2.7.0
Location: /usr/local/lib/python2.7/dist-packages
Requires: 
```

**Comment by jflesch** [comment]
Darn. It's a change they made in python-whoosh ...

**Comment by jflesch** [comment]
Just so you know, while I fix this, if you can go back to python-whoosh 2.6.x, things should work again.

**Comment by jflesch** [comment]
Planned patch:

```
diff --git a/src/paperwork/backend/docsearch.py b/src/paperwork/backend/docsearch.py
index ae79bee..6998af2 100644
--- a/src/paperwork/backend/docsearch.py
+++ b/src/paperwork/backend/docsearch.py
@@ -319,7 +319,7 @@ class DocSearch(object):
         docfilehash=whoosh.fields.ID(stored=True),
         content=whoosh.fields.TEXT(spelling=True),
         label=whoosh.fields.KEYWORD(stored=True, commas=True,
-                                    spelling=True, scorable=True),
+                                    scorable=True),
         date=whoosh.fields.DATETIME(stored=True),
         last_read=whoosh.fields.DATETIME(stored=True),
     )
```

I need to make sure it does not create any other bug before releasing a 0.2.4 with it.

**Comment by mathieumd** [comment]
I applied your fix, and things seems alright for now. Thanks!

**Comment by jflesch** [comment]
88aed3f36bfce58898a310adc938c6d5161cdbd6
