### ISSUE TITLE
Moving a page to a new document fails

### ISSUE THREAD

**Issue by jflesch** [jflesch/paperwork#419]
```
Traceback (most recent call last):
  File "/home/jflesch/Private/git/paperwork/src/paperwork/frontend/mainwindow/docs.py", line 708, in _on_drag_motion
    target_doc = self.__main_win.docsearch.get(target_docid)
  File "/home/jflesch/Private/git/paperwork/src/paperwork/backend/docsearch.py", line 578, in get
    return self.__docs_by_id[obj_id]
KeyError: '20151210_1523_11'
INFO   paperwork.frontend.mainwindow.pages Drag-n-drop get: selected: [20151207_1646_35|0]
INFO   paperwork.frontend.mainwindow.docs Drag-n-drop data received on doc list: [20151207_1646_35|0] --> [20151210_1523_11]
Traceback (most recent call last):
  File "/home/jflesch/Private/git/paperwork/src/paperwork/frontend/mainwindow/docs.py", line 738, in _on_drag_data_received
    target_doc = self.__main_win.docsearch.get(target_docid)
  File "/home/jflesch/Private/git/paperwork/src/paperwork/backend/docsearch.py", line 578, in get
    return self.__docs_by_id[obj_id]
```

**Comment by jflesch** [comment]
Can't reproduce

**Comment by jflesch** [comment]
Misread the ticket

**Comment by jflesch** [comment]
5e4a7e0ed03615645c802df85dc44b00ab8a347a
