### ISSUE TITLE
ubuntu install problem

### ISSUE THREAD

**Issue by kforner** [jflesch/paperwork#431]
After following the ubuntu install instructions, I finally managed to get paperwork installed.
I installed the extra deps as reported by `paperwork-chkdeps`.

But when I execute paperwork:
```
> paperwork
RuntimeError: module compiled against API version 9 but this version of numpy is 7
Traceback (most recent call last):
  File "/usr/local/bin/paperwork", line 3, in <module>
    from paperwork.paperwork import main
  File "/usr/local/lib/python2.7/dist-packages/paperwork/paperwork.py", line 31, in <module>
    from frontend.mainwindow import ActionRefreshIndex, MainWindow
  File "/usr/local/lib/python2.7/dist-packages/paperwork/frontend/mainwindow/__init__.py", line 61, in <module>
    from paperwork.backend import docimport
  File "/usr/local/lib/python2.7/dist-packages/paperwork/backend/docimport.py", line 30, in <module>
    from paperwork.backend.pdf.doc import PdfDoc
  File "/usr/local/lib/python2.7/dist-packages/paperwork/backend/pdf/doc.py", line 26, in <module>
    from paperwork.backend.common.doc import BasicDoc
  File "/usr/local/lib/python2.7/dist-packages/paperwork/backend/common/doc.py", line 25, in <module>
    from scipy import sparse
  File "/usr/lib/python2.7/dist-packages/scipy/sparse/__init__.py", line 206, in <module>
    from .csr import *
  File "/usr/lib/python2.7/dist-packages/scipy/sparse/csr.py", line 15, in <module>
    from .sparsetools import csr_tocsc, csr_tobsr, csr_count_blocks, \
  File "/usr/lib/python2.7/dist-packages/scipy/sparse/sparsetools/__init__.py", line 5, in <module>
    from .csr import *
  File "/usr/lib/python2.7/dist-packages/scipy/sparse/sparsetools/csr.py", line 28, in <module>
    _csr = swig_import_helper()
  File "/usr/lib/python2.7/dist-packages/scipy/sparse/sparsetools/csr.py", line 24, in swig_import_helper
    _mod = imp.load_module('_csr', fp, pathname, description)
ImportError: numpy.core.multiarray failed to import
```

I kind of imagine this is due to multiple conflicting versions of python.
```
> dpkg -l | grep -i "python language"
ii  libpython2.7-minimal:amd64                                  2.7.6-8ubuntu0.2                                    amd64        Minimal subset of the Python language (version 2.7)
ii  libpython3.4-minimal:amd64                                  3.4.0-2ubuntu1                                      amd64        Minimal subset of the Python language (version 3.4)
ii  python-cloudfiles                                           1.7.11-2build1                                      all          Python language bindings for Cloud Files API
ii  python-minimal                                              2.7.5-5ubuntu3                                      amd64        minimal subset of the Python language (default version)
ii  python-numpy                                                1:1.8.2-0ubuntu0.1                                  amd64        Numerical Python adds a fast array facility to the Python language
ii  python2.7-minimal                                           2.7.6-8ubuntu0.2                                    amd64        Minimal subset of the Python language (version 2.7)
ii  python3-minimal                                             3.4.0-0ubuntu2                                      amd64        minimal subset of the Python language (default python3 version)
ii  python3.4-minimal                                           3.4.0-2ubuntu1                                      amd64        Minimal subset of the Python language (version 3.4)
```

**Comment by jflesch** [comment]
Well, the good news is that Paperwork 0.3.0 (and later) won't need numpy, scikit & co anymore. They have always been a pain.
Also, I intend to release Paperwork 0.3.0 at the end of this month, so I'm even wondering if it's worth trying to fix this issue ...

**Comment by kforner** [comment]
sure
