### ISSUE TITLE
paperwork: permission denied and noneType attribute get_hagustment

### ISSUE THREAD

**Issue by ajira86** [jflesch/paperwork#455]
Hello,

I tried to install paperwork from Debian Stretch and got this result:

```
$ sudo pip install paperwork
Collecting paperwork
Requirement already satisfied (use --upgrade to upgrade): python-Levenshtein in /usr/local/lib/python2.7/dist-packages (from paperwork)
Requirement already satisfied (use --upgrade to upgrade): pyinsane>=1.3.8 in /usr/local/lib/python2.7/dist-packages (from paperwork)
Requirement already satisfied (use --upgrade to upgrade): Pillow in /usr/lib/python2.7/dist-packages (from paperwork)
Requirement already satisfied (use --upgrade to upgrade): pyenchant in /usr/local/lib/python2.7/dist-packages (from paperwork)
Requirement already satisfied (use --upgrade to upgrade): termcolor in /usr/local/lib/python2.7/dist-packages (from paperwork)
Requirement already satisfied (use --upgrade to upgrade): pyocr>=0.3.0 in /usr/local/lib/python2.7/dist-packages (from paperwork)
Requirement already satisfied (use --upgrade to upgrade): simplebayes in /usr/local/lib/python2.7/dist-packages (from paperwork)
Requirement already satisfied (use --upgrade to upgrade): pycountry in /usr/local/lib/python2.7/dist-packages (from paperwork)
Requirement already satisfied (use --upgrade to upgrade): Whoosh in /usr/local/lib/python2.7/dist-packages (from paperwork)
Requirement already satisfied (use --upgrade to upgrade): setuptools in /usr/lib/python2.7/dist-packages (from python-Levenshtein->paperwork)
Installing collected packages: paperwork
Successfully installed paperwork-0.3.0.1

$ paperwork
bash: /usr/local/bin/paperwork: Permission denied

$ paperwork-chkdeps
bash: /usr/local/bin/paperwork-chkdeps: Permission denied
```

So after this I put chmod +x on paperwork and paperwork-chkdeps, I installed dependences and relaunch but got this error:

```
$ paperwork
INFO   paperwork.paperwork            Looking for locales in 'locale/fr/LC_MESSAGES/paperwork.mo' ...
INFO   paperwork.paperwork            Looking for locales in '/usr/local/share/locale/fr/LC_MESSAGES/paperwork.mo' ...
INFO   paperwork.paperwork            Looking for locales in '/usr/share/locale/fr/LC_MESSAGES/paperwork.mo' ...
INFO   paperwork.paperwork            Will use locales from '/usr/share/locale'
INFO   paperwork.backend.config       Config file found: /home/samuel/.config/paperwork.conf
INFO   paperwork.backend.config       Reloading /home/samuel/.config/paperwork.conf ...
INFO   paperwork.frontend.util        UI file used: /usr/share/paperwork/mainwindow/appmenu.xml
INFO   paperwork.frontend.util        CSS file used: /usr/local/lib/python2.7/dist-packages/usr/share/paperwork/application.css
INFO   paperwork.frontend.util        UI file used: /usr/share/paperwork/mainwindow/mainwindow.glade
INFO   paperwork.paperwork            Good bye
Traceback (most recent call last):
  File "/usr/local/bin/paperwork", line 6, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/paperwork/paperwork.py", line 112, in main
    main_win = MainWindow(config)
  File "/usr/local/lib/python2.7/dist-packages/paperwork/frontend/mainwindow/__init__.py", line 1878, in __init__
    self.doclist = DocList(self, config, widget_tree)
  File "/usr/local/lib/python2.7/dist-packages/paperwork/frontend/mainwindow/docs.py", line 531, in __init__
    self.gui['loading'] = Canvas(self.gui['scrollbars'])
  File "/usr/local/lib/python2.7/dist-packages/paperwork/frontend/util/canvas/__init__.py", line 78, in __init__
    hadj = scrollbars.get_hadjustment()
AttributeError: 'NoneType' object has no attribute 'get_hadjustment'
```

**Comment by jflesch** [comment]
1) The missing executable bit is weird. Pip/setuptools should take care of that

2) The Python exception happens sometimes when Paperwork stops. I haven't figured out why yet. But it's a non-blocking issue.

3 ) Now, your logs are strange : Did Paperwork just start and stopped immediately on its own ?

**Comment by ajira86** [comment]
Nothing on the screen, this is why I launched it from terminal.
I was running an old version of paperwork before re-install to 0.3.1.
Could it come from bad settings ?

**Comment by jflesch** [comment]
This is really weird. I'm running Debian Stretch at home and everything work fine.

What you can try (as root), just to be sure it's not an older version that create troubles:

```
pip uninstall paperwork  # many times, until it says there is nothing installed anymore
pip uninstall pyocr  # many times, until it says there is nothing installed anymore
pip uninstall pyinsane  # many times, until it says there is nothing installed anymore
rm -rf /usr/local/lib/python2.7/dist-packages/paperwork*
rm -rf /usr/local/lib/python2.7/dist-packages/pyocr*
rm -rf /usr/local/lib/python2.7/dist-packages/pyinsane*
```

Then reinstall Paperwork.

**Comment by jflesch** [comment]
I forgot:
```
rm -rf /usr/share/paperwork /usr/local/share/paperwork
```

**Comment by jflesch** [comment]
Also, maybe running ```PAPERWORK_VERBOSE=DEBUG paperwork``` instead of just ```paperwork``` will give you more information.

**Comment by ajira86** [comment]
FYI after all your uninstall commands I launch a search and got this answer:

```
$ sudo find / -name "*paperwork*"
/root/.cache/pip/wheels/61/e8/8e/862f721446ce08b6e51836924e621cca19550dfca324f93d7c/paperwork-0.2-cp27-none-any.whl
/root/.cache/pip/wheels/4b/39/5b/b45df230189598cf6cb627c05b223a5e6479740de6145bd47a/paperwork-0.3.0.1-cp27-none-any.whl
/home/samuel/.local/share/paperwork
/home/samuel/.cache/pip/wheels/4b/39/5b/b45df230189598cf6cb627c05b223a5e6479740de6145bd47a/paperwork-0.3.0.1-cp27-none-any.whl
/home/samuel/.config/paperwork.conf
find: ‘/run/user/1000/gvfs’: Permission denied
/usr/share/locale/fr/LC_MESSAGES/paperwork.mo
/usr/share/locale/de/LC_MESSAGES/paperwork.mo
/usr/share/applications/paperwork.desktop
/usr/share/icons/paperwork.svg
```

Now I have this:
```
$ sudo pip install paperwork
Collecting paperwork
  Downloading paperwork-0.3.1.tar.gz (164kB)
    100% |████████████████████████████████| 167kB 2.3MB/s 
Collecting python<3 (from paperwork)
  Could not find a version that satisfies the requirement python<3 (from paperwork) (from versions: )
No matching distribution found for python<3 (from paperwork)
```

So I have python 2.7 and python > 3.5 installed
If I call python --version, I got 2.7.11+ by default. Should I switch for python 3.5 ?

**Comment by jflesch** [comment]
Darn

**Comment by jflesch** [comment]
No it was a mistake from me (because of this ticket : #450 ).
I've released a 0.3.1.1 to fix it.
Sorry for the mess.

**Comment by ajira86** [comment]
Great, now it's working for me with version 0.3.1.1
Apparently the migration between paperwork before 0.3 and after 0.3 can cause issues but which ?

**Comment by jflesch** [comment]
Ok, I'm closing this ticket. Please reopen if you have this problem again.
