### ISSUE TITLE
Updating dates

### ISSUE THREAD

**Issue by smurfix** [jflesch/paperwork#457]
* edit properties, change date, switch back to thumbnail view
* edit properties again, change dates, switch back … oops, doesn't work, paperwork forgot to update its own idea of the date:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/paperwork/frontend/util/actions.py", line 67, in on_button_clicked_cb
    return self.__do()
  File "/usr/lib/python2.7/dist-packages/paperwork/frontend/util/actions.py", line 64, in __do
    return self.do(**kwargs)
  File "/usr/lib/python2.7/dist-packages/paperwork/frontend/mainwindow/docs.py", line 392, in do
    self.__main_win.doc_properties_panel.apply_properties()
  File "/usr/lib/python2.7/dist-packages/paperwork/frontend/mainwindow/docs.py", line 1124, in apply_properties
    self.doc.extra_text = new_extra_text
  File "/usr/lib/python2.7/dist-packages/paperwork/backend/common/doc.py", line 386, in __set_extra_text
    encoding='utf-8') as file_desc:
  File "/usr/lib/python2.7/codecs.py", line 878, in open
    file = __builtin__.open(filename, mode, buffering)
IOError: [Errno 2] No such file or directory: u'/home/smurf/papers/20150101_0000_01/extra.txt'

```

* need to restart paperwork

**Comment by jflesch** [comment]
08ae43cf4b7d259580c572b0fe96c689297ee041
