### ISSUE TITLE
Paperwork does not start, AttributeError: 'NoneType' object has no attribute 'pack_end'

### ISSUE THREAD

**Issue by nodiscc** [jflesch/paperwork#460]
Hi, after installing paperwork on Debian testing, following the procedure I posted [here](https://github.com/jflesch/paperwork/issues/459), the program does not start and throws an error:

```
$ paperwork 

** (paperwork:4890): WARNING **: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files
/usr/local/lib/python2.7/dist-packages/paperwork/paperwork.py:25: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk
/usr/local/lib/python2.7/dist-packages/paperwork/frontend/mainwindow/pages.py:22: PyGIWarning: PangoCairo was imported without specifying a version first. Use gi.require_version('PangoCairo', '1.0') before import to ensure that the right version gets loaded.
  from gi.repository import PangoCairo
/usr/local/lib/python2.7/dist-packages/paperwork/backend/docimport.py:27: PyGIWarning: Poppler was imported without specifying a version first. Use gi.require_version('Poppler', '0.18') before import to ensure that the right version gets loaded.
  from gi.repository import Poppler
INFO   paperwork.paperwork            Looking for locales in 'locale/fr/LC_MESSAGES/paperwork.mo' ...
INFO   paperwork.paperwork            Looking for locales in '/usr/local/share/locale/fr/LC_MESSAGES/paperwork.mo' ...
INFO   paperwork.paperwork            Looking for locales in '/usr/share/locale/fr/LC_MESSAGES/paperwork.mo' ...
INFO   root                           Will use locales from '/usr/share/locale'
/usr/local/lib/python2.7/dist-packages/paperwork/paperwork.py:97: PyGIDeprecationWarning: Since version 3.11, calling threads_init is no longer needed. See: https://wiki.gnome.org/PyGObject/Threading
  GObject.threads_init()
INFO   paperwork.backend.config       Config file found: /home/test/.config/paperwork.conf
INFO   paperwork.backend.config       Reloading /home/test/.config/paperwork.conf ...
INFO   root                           UI file used: /usr/share/paperwork/mainwindow/appmenu.xml
INFO   root                           UI file used: /usr/share/paperwork/mainwindow/mainwindow.glade
INFO   paperwork.paperwork            Good bye
Traceback (most recent call last):
  File "/usr/local/bin/paperwork", line 6, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/paperwork/paperwork.py", line 109, in main
    main_win = MainWindow(config)
  File "/usr/local/lib/python2.7/dist-packages/paperwork/frontend/mainwindow/__init__.py", line 2443, in __init__
    iconview_matches.pack_end(cellrenderer_labels, True)
AttributeError: 'NoneType' object has no attribute 'pack_end'

$
```

**Comment by jflesch** [comment]
Did you upgrade from a previous version of Paperwork ?

**Comment by nodiscc** [comment]
Thank you. I Had another `paperwork` installed a while ago through pip. After removing it and retrying to run paperwork I had `ImportError: No module named simplebayes` -> `sudo pypi-install simplebayes`, the retried:

```
$ paperwork
[...]
INFO   paperwork.backend.config       Reloading /home/test/.config/paperwork.conf ...
ERROR  paperwork.frontend.util        Can't find resource file 'mainwindow/appmenu.xml'. Aborting
INFO   paperwork.paperwork            Good bye
Traceback (most recent call last):
  File "/usr/bin/paperwork", line 6, in <module>
    main()
  File "/usr/lib/python2.7/dist-packages/paperwork/paperwork.py", line 112, in main
    main_win = MainWindow(config)
  File "/usr/lib/python2.7/dist-packages/paperwork/frontend/mainwindow/__init__.py", line 1869, in __init__
    self.__advanced_app_menu = self.__init_app_menu(self.app)
  File "/usr/lib/python2.7/dist-packages/paperwork/frontend/mainwindow/__init__.py", line 2353, in __init_app_menu
    app_menu = load_uifile(os.path.join("mainwindow", "appmenu.xml"))
  File "/usr/lib/python2.7/dist-packages/paperwork/frontend/util/__init__.py", line 74, in load_uifile
    raise Exception("Can't find resource file '%s'. Aborting" % filename)
Exception: Can't find resource file 'mainwindow/appmenu.xml'. Aborting
```

**Comment by jflesch** [comment]
After uninstalling the previous version of Paperwork, did you reinstall the new one ?

**Comment by nodiscc** [comment]
Ewww no I had not. After redoing `sudo pypi-install paperwork` the problem is fixed (as well as https://github.com/jflesch/paperwork/issues/459). Wish I had known about `pypi-install` earlier...

Merci!
