### ISSUE TITLE
Multicore OCR

### ISSUE THREAD

**Issue by VorpalBlade** [jflesch/paperwork#463]
When importing a directory with many PDFs (with many pages each) on a system with a multi-core CPU more than one tesseract process should probably be executed. This seems like an easy way to increase performance by adding parallelism.

Considering how long it takes for tesseract to process a single page this would save a lot of time.

**Comment by jflesch** [comment]
Related to #51

**Comment by toerb** [comment]
@jflesch I have done some work to enable multiprocessing from paperwork-shell.

You can see my current progressing in my develop branch: https://github.com/toerb/paperwork-backend/tree/develop

Passing the page objects to the processes from multiprocessing pool is working.
Unfortunately the resulting page object is not pickable and throws the following error:

```
Running OCR on 20180204_1913_43|0 ...
Running OCR on 20180204_1913_43|2 ...
Running OCR on 20180204_1913_43|1 ...
Running OCR on 20180204_1913_43|3 ...
Running OCR on 20180204_1913_43|4 ...
{
    "args": "('\\'TypeError(\"can\\\\\\'t pickle Document objects\",)\\'', \"'20180204_1913_43 p1'\")",
    "exception": "<class 'multiprocessing.pool.MaybeEncodingError'>",
    "reason": "Error sending result: '20180204_1913_43 p1'. Reason: 'TypeError(\"can't pickle Document objects\",)'",
    "status": "error"
}
Traceback (most recent call last):
  File "/usr/bin/paperwork-shell", line 11, in <module>
    load_entry_point('paperwork-backend==1.2.2', 'console_scripts', 'paperwork-shell')()
  File "/usr/lib/python3.6/site-packages/paperwork_backend/shell_cmd.py", line 214, in main
    sys.exit(COMMANDS[args.cmd](*args.cmd_args))
  File "/usr/lib/python3.6/site-packages/paperwork_backend/shell.py", line 618, in cmd_import
    return _do_import(args, dsearch, doc, ocr, ocr_lang, guess_labels)
  File "/usr/lib/python3.6/site-packages/paperwork_backend/shell.py", line 482, in _do_import
    for page in results:
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 735, in next
    raise value
multiprocessing.pool.MaybeEncodingError: Error sending result: '20180204_1913_43 p1'. Reason: 'TypeError("can't pickle Document objects",)'
```

Do you have any idea how this can be solved?

**Comment by jflesch** [comment]
> can't pickle Document objects

The only objects called `Document` come from Poppler. They cannot be pickled (they are gobject bindings). However, currenty, page objects don't keep any reference to Poppler objects, so pickling shouldn't be a problem here :/

**Comment by jflesch** [comment]
BTW, wouldn't it be more useful to modify `PdfDirectoryImporter` instead of the command shell `import` itself ?

**Comment by toerb** [comment]
ocr is atm done in the `import` and `ocr` shell subcommands so this was just the first possibility for me to intersect with this behaviour.
Do you think this feature would be cleaner implemented in `PdfDirectoryImporter` and remove the ocr part in the `import` subcommand but keep it in the `ocr` subcommand?

Alternatively the `_do_ocr` function could be altered to only return the page_id since only this is needed in the `import` subcommand. I try this tomorrow.

**Comment by toerb** [comment]
I fixed the issue with the multiprocessing return queue and the Document object by only returning the pageid.

You can find the pull request [here](https://github.com/openpaperwork/paperwork-backend/pull/7).

Here are some tests with a 32 page PDF and singlethreaded vs. multithreaded (4 threads).
My CPU: Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz

## Import with 1 process
**406 seconds**
```
[toerb@mittagspause ~]$ date ;time paperwork-shell import -- /home/scan/new/ --no_ocr --no_label_guessing; date
Mo 5. Feb 08:29:05 CET 2018
Work directory: file:///mnt/dokumente/paperwork
Files ['file:///home/scan/new']: Importer = Import each PDF in the folder as a new document
['file:///home/scan/new']:
Running OCR on page 20180205_0829_06|0
Running OCR on page 20180205_0829_06|1
Running OCR on page 20180205_0829_06|2
Running OCR on page 20180205_0829_06|3
Running OCR on page 20180205_0829_06|4
Running OCR on page 20180205_0829_06|5
Running OCR on page 20180205_0829_06|6
Running OCR on page 20180205_0829_06|7
Running OCR on page 20180205_0829_06|8
Running OCR on page 20180205_0829_06|9
Running OCR on page 20180205_0829_06|10
Running OCR on page 20180205_0829_06|11
Running OCR on page 20180205_0829_06|12
Running OCR on page 20180205_0829_06|13
Running OCR on page 20180205_0829_06|14
Running OCR on page 20180205_0829_06|15
Running OCR on page 20180205_0829_06|16
Running OCR on page 20180205_0829_06|17
Running OCR on page 20180205_0829_06|18
Running OCR on page 20180205_0829_06|19
Running OCR on page 20180205_0829_06|20
Running OCR on page 20180205_0829_06|21
Running OCR on page 20180205_0829_06|22
Running OCR on page 20180205_0829_06|23
Running OCR on page 20180205_0829_06|24
Running OCR on page 20180205_0829_06|25
Running OCR on page 20180205_0829_06|26
Running OCR on page 20180205_0829_06|27
Running OCR on page 20180205_0829_06|28
Running OCR on page 20180205_0829_06|29
Running OCR on page 20180205_0829_06|30
Running OCR on page 20180205_0829_06|31
Document 20180205_0829_06 (labels: )
Updating index ...
Done
{
    "guessed_labels": [],
    "imports": {
        "imported_file_uris": [
            "file:///home/scan/new/20180204_124315_000652.pdf"
        ],
        "new_docs": [
            {
                "docid": "20180205_0829_06",
                "labels": []
            }
        ],
        "new_docs_pages": [
            "20180205_0829_06|0",
            "20180205_0829_06|1",
            "20180205_0829_06|2",
            "20180205_0829_06|3",
            "20180205_0829_06|4",
            "20180205_0829_06|5",
            "20180205_0829_06|6",
            "20180205_0829_06|7",
            "20180205_0829_06|8",
            "20180205_0829_06|9",
            "20180205_0829_06|10",
            "20180205_0829_06|11",
            "20180205_0829_06|12",
            "20180205_0829_06|13",
            "20180205_0829_06|14",
            "20180205_0829_06|15",
            "20180205_0829_06|16",
            "20180205_0829_06|17",
            "20180205_0829_06|18",
            "20180205_0829_06|19",
            "20180205_0829_06|20",
            "20180205_0829_06|21",
            "20180205_0829_06|22",
            "20180205_0829_06|23",
            "20180205_0829_06|24",
            "20180205_0829_06|25",
            "20180205_0829_06|26",
            "20180205_0829_06|27",
            "20180205_0829_06|28",
            "20180205_0829_06|29",
            "20180205_0829_06|30",
            "20180205_0829_06|31"
        ],
        "stats": {
            "Document(s)": 1,
            "Image file(s)": 0,
            "PDF": 1,
            "Page(s)": 32
        },
        "upd_docs": [],
        "upd_docs_pages": []
    },
    "ocr": [
        "20180205_0829_06|0",
        "20180205_0829_06|1",
        "20180205_0829_06|2",
        "20180205_0829_06|3",
        "20180205_0829_06|4",
        "20180205_0829_06|5",
        "20180205_0829_06|6",
        "20180205_0829_06|7",
        "20180205_0829_06|8",
        "20180205_0829_06|9",
        "20180205_0829_06|10",
        "20180205_0829_06|11",
        "20180205_0829_06|12",
        "20180205_0829_06|13",
        "20180205_0829_06|14",
        "20180205_0829_06|15",
        "20180205_0829_06|16",
        "20180205_0829_06|17",
        "20180205_0829_06|18",
        "20180205_0829_06|19",
        "20180205_0829_06|20",
        "20180205_0829_06|21",
        "20180205_0829_06|22",
        "20180205_0829_06|23",
        "20180205_0829_06|24",
        "20180205_0829_06|25",
        "20180205_0829_06|26",
        "20180205_0829_06|27",
        "20180205_0829_06|28",
        "20180205_0829_06|29",
        "20180205_0829_06|30",
        "20180205_0829_06|31"
    ],
    "status": "ok"
}

real	6m46,747s
user	6m39,933s
sys	0m4,829s
Mo 5. Feb 08:35:52 CET 2018
```

## Import with 4 processes on dualcore CPU with HT
**190 seconds**
```
[toerb@mittagspause ~]$ date ;time paperwork-shell import -- /home/scan/new/ --no_ocr --no_label_guessing; date
Mo 5. Feb 08:25:04 CET 2018
Work directory: file:///mnt/dokumente/paperwork
Files ['file:///home/scan/new']: Importer = Import each PDF in the folder as a new document
['file:///home/scan/new']:
Running OCR on 20180205_0825_05|2 ...
Running OCR on 20180205_0825_05|0 ...
Running OCR on 20180205_0825_05|1 ...
Running OCR on 20180205_0825_05|3 ...
Running OCR on 20180205_0825_05|4 ...
Running OCR on 20180205_0825_05|5 ...
Running OCR on 20180205_0825_05|6 ...
Running OCR on 20180205_0825_05|7 ...
Running OCR on 20180205_0825_05|8 ...
Running OCR on 20180205_0825_05|9 ...
Running OCR on 20180205_0825_05|10 ...
Running OCR on 20180205_0825_05|11 ...
Running OCR on 20180205_0825_05|12 ...
Running OCR on 20180205_0825_05|13 ...
Running OCR on 20180205_0825_05|14 ...
Running OCR on 20180205_0825_05|15 ...
Running OCR on 20180205_0825_05|16 ...
Running OCR on 20180205_0825_05|17 ...
Running OCR on 20180205_0825_05|18 ...
Running OCR on 20180205_0825_05|19 ...
Running OCR on 20180205_0825_05|20 ...
Running OCR on 20180205_0825_05|21 ...
Running OCR on 20180205_0825_05|22 ...
Running OCR on 20180205_0825_05|23 ...
Running OCR on 20180205_0825_05|24 ...
Running OCR on 20180205_0825_05|25 ...
Running OCR on 20180205_0825_05|26 ...
Running OCR on 20180205_0825_05|27 ...
Running OCR on 20180205_0825_05|28 ...
Running OCR on 20180205_0825_05|29 ...
Running OCR on 20180205_0825_05|30 ...
Running OCR on 20180205_0825_05|31 ...
Document 20180205_0825_05 (labels: )
Updating index ...
Done
{
    "guessed_labels": [],
    "imports": {
        "imported_file_uris": [
            "file:///home/scan/new/20180204_124315_000652.pdf"
        ],
        "new_docs": [
            {
                "docid": "20180205_0825_05",
                "labels": []
            }
        ],
        "new_docs_pages": [
            "20180205_0825_05|0",
            "20180205_0825_05|1",
            "20180205_0825_05|2",
            "20180205_0825_05|3",
            "20180205_0825_05|4",
            "20180205_0825_05|5",
            "20180205_0825_05|6",
            "20180205_0825_05|7",
            "20180205_0825_05|8",
            "20180205_0825_05|9",
            "20180205_0825_05|10",
            "20180205_0825_05|11",
            "20180205_0825_05|12",
            "20180205_0825_05|13",
            "20180205_0825_05|14",
            "20180205_0825_05|15",
            "20180205_0825_05|16",
            "20180205_0825_05|17",
            "20180205_0825_05|18",
            "20180205_0825_05|19",
            "20180205_0825_05|20",
            "20180205_0825_05|21",
            "20180205_0825_05|22",
            "20180205_0825_05|23",
            "20180205_0825_05|24",
            "20180205_0825_05|25",
            "20180205_0825_05|26",
            "20180205_0825_05|27",
            "20180205_0825_05|28",
            "20180205_0825_05|29",
            "20180205_0825_05|30",
            "20180205_0825_05|31"
        ],
        "stats": {
            "Document(s)": 1,
            "Image file(s)": 0,
            "PDF": 1,
            "Page(s)": 32
        },
        "upd_docs": [],
        "upd_docs_pages": []
    },
    "ocr": [
        "20180205_0825_05|0",
        "20180205_0825_05|3",
        "20180205_0825_05|2",
        "20180205_0825_05|1",
        "20180205_0825_05|4",
        "20180205_0825_05|7",
        "20180205_0825_05|5",
        "20180205_0825_05|9",
        "20180205_0825_05|8",
        "20180205_0825_05|10",
        "20180205_0825_05|12",
        "20180205_0825_05|11",
        "20180205_0825_05|13",
        "20180205_0825_05|14",
        "20180205_0825_05|16",
        "20180205_0825_05|15",
        "20180205_0825_05|19",
        "20180205_0825_05|18",
        "20180205_0825_05|17",
        "20180205_0825_05|20",
        "20180205_0825_05|21",
        "20180205_0825_05|22",
        "20180205_0825_05|23",
        "20180205_0825_05|25",
        "20180205_0825_05|24",
        "20180205_0825_05|26",
        "20180205_0825_05|6",
        "20180205_0825_05|28",
        "20180205_0825_05|29",
        "20180205_0825_05|31",
        "20180205_0825_05|30",
        "20180205_0825_05|27"
    ],
    "status": "ok"
}

real	3m10,566s
user	10m31,595s
sys	0m7,582s
Mo 5. Feb 08:28:14 CET 2018
```

## OCR on fresh imported document without OCR on single CPU
**446 seconds**
```
[toerb@mittagspause ~]$ date ;time paperwork-shell ocr 20180205_0847_26; date
Mo 5. Feb 08:47:42 CET 2018
Work directory: file:///mnt/dokumente/paperwork
Running OCR on 20180205_0847_26|22 ...
Running OCR on 20180205_0847_26|13 ...
Running OCR on 20180205_0847_26|8 ...
Running OCR on 20180205_0847_26|1 ...
Running OCR on 20180205_0847_26|30 ...
Running OCR on 20180205_0847_26|4 ...
Running OCR on 20180205_0847_26|24 ...
Running OCR on 20180205_0847_26|26 ...
Running OCR on 20180205_0847_26|2 ...
Running OCR on 20180205_0847_26|20 ...
Running OCR on 20180205_0847_26|11 ...
Running OCR on 20180205_0847_26|10 ...
Running OCR on 20180205_0847_26|17 ...
Running OCR on 20180205_0847_26|15 ...
Running OCR on 20180205_0847_26|29 ...
Running OCR on 20180205_0847_26|0 ...
Running OCR on 20180205_0847_26|14 ...
Running OCR on 20180205_0847_26|5 ...
Running OCR on 20180205_0847_26|31 ...
Running OCR on 20180205_0847_26|28 ...
Running OCR on 20180205_0847_26|18 ...
Running OCR on 20180205_0847_26|19 ...
Running OCR on 20180205_0847_26|9 ...
Running OCR on 20180205_0847_26|25 ...
Running OCR on 20180205_0847_26|27 ...
Running OCR on 20180205_0847_26|3 ...
Running OCR on 20180205_0847_26|6 ...
Running OCR on 20180205_0847_26|21 ...
Running OCR on 20180205_0847_26|23 ...
Running OCR on 20180205_0847_26|12 ...
Running OCR on 20180205_0847_26|7 ...
Running OCR on 20180205_0847_26|16 ...
Updating index ...
Done
{
    "ocr": [
        "20180205_0847_26|22",
        "20180205_0847_26|13",
        "20180205_0847_26|8",
        "20180205_0847_26|1",
        "20180205_0847_26|30",
        "20180205_0847_26|4",
        "20180205_0847_26|24",
        "20180205_0847_26|26",
        "20180205_0847_26|2",
        "20180205_0847_26|20",
        "20180205_0847_26|11",
        "20180205_0847_26|10",
        "20180205_0847_26|17",
        "20180205_0847_26|15",
        "20180205_0847_26|29",
        "20180205_0847_26|0",
        "20180205_0847_26|14",
        "20180205_0847_26|5",
        "20180205_0847_26|31",
        "20180205_0847_26|28",
        "20180205_0847_26|18",
        "20180205_0847_26|19",
        "20180205_0847_26|9",
        "20180205_0847_26|25",
        "20180205_0847_26|27",
        "20180205_0847_26|3",
        "20180205_0847_26|6",
        "20180205_0847_26|21",
        "20180205_0847_26|23",
        "20180205_0847_26|12",
        "20180205_0847_26|7",
        "20180205_0847_26|16"
    ],
    "status": "ok"
}

real	7m26,224s
user	7m19,794s
sys	0m5,089s
Mo 5. Feb 08:55:09 CET 2018
```

## OCR on fresh imported document without OCR with 4 processes on dualcore CPU with HT
**170 seconds**
```
[toerb@mittagspause ~]$ date ;time paperwork-shell ocr 20180205_0840_51; date
Mo 5. Feb 08:41:04 CET 2018
Work directory: file:///mnt/dokumente/paperwork
Running OCR on 20180205_0840_51|7 ...
Running OCR on 20180205_0840_51|6 ...
Running OCR on 20180205_0840_51|14 ...
Running OCR on 20180205_0840_51|1 ...
Running OCR on 20180205_0840_51|13 ...
Running OCR on 20180205_0840_51|3 ...
Running OCR on 20180205_0840_51|4 ...
Running OCR on 20180205_0840_51|5 ...
Running OCR on 20180205_0840_51|21 ...
Running OCR on 20180205_0840_51|19 ...
Running OCR on 20180205_0840_51|2 ...
Running OCR on 20180205_0840_51|8 ...
Running OCR on 20180205_0840_51|16 ...
Running OCR on 20180205_0840_51|23 ...
Running OCR on 20180205_0840_51|10 ...
Running OCR on 20180205_0840_51|22 ...
Running OCR on 20180205_0840_51|25 ...
Running OCR on 20180205_0840_51|0 ...
Running OCR on 20180205_0840_51|27 ...
Running OCR on 20180205_0840_51|28 ...
Running OCR on 20180205_0840_51|30 ...
Running OCR on 20180205_0840_51|26 ...
Running OCR on 20180205_0840_51|31 ...
Running OCR on 20180205_0840_51|20 ...
Running OCR on 20180205_0840_51|24 ...
Running OCR on 20180205_0840_51|29 ...
Running OCR on 20180205_0840_51|15 ...
Running OCR on 20180205_0840_51|17 ...
Running OCR on 20180205_0840_51|12 ...
Running OCR on 20180205_0840_51|9 ...
Running OCR on 20180205_0840_51|18 ...
Running OCR on 20180205_0840_51|11 ...
Updating index ...
Done
{
    "ocr": [
        "20180205_0840_51|7",
        "20180205_0840_51|6",
        "20180205_0840_51|14",
        "20180205_0840_51|1",
        "20180205_0840_51|13",
        "20180205_0840_51|3",
        "20180205_0840_51|4",
        "20180205_0840_51|5",
        "20180205_0840_51|21",
        "20180205_0840_51|19",
        "20180205_0840_51|2",
        "20180205_0840_51|8",
        "20180205_0840_51|16",
        "20180205_0840_51|23",
        "20180205_0840_51|10",
        "20180205_0840_51|22",
        "20180205_0840_51|25",
        "20180205_0840_51|0",
        "20180205_0840_51|27",
        "20180205_0840_51|28",
        "20180205_0840_51|30",
        "20180205_0840_51|26",
        "20180205_0840_51|31",
        "20180205_0840_51|20",
        "20180205_0840_51|24",
        "20180205_0840_51|29",
        "20180205_0840_51|15",
        "20180205_0840_51|17",
        "20180205_0840_51|12",
        "20180205_0840_51|9",
        "20180205_0840_51|18",
        "20180205_0840_51|11"
    ],
    "status": "ok"
}

real	2m49,793s
user	10m44,366s
sys	0m7,444s
Mo 5. Feb 08:43:54 CET 2018
```

**Comment by jflesch** [comment]
> ocr is atm done in the import and ocr shell subcommands so this was just the first possibility for me to intersect with this behaviour.

Nevermind :)
I forgot that `docimport.PdfDirectoryImporter` only did the actual import and not the OCR.

**Comment by toerb** [comment]
For documentation now with threaded implementation:

## Import with 4 threads on dualcore CPU with HT
**215 seconds**
```
[toerb@mittagspause ~]$ date ;time paperwork-shell import -- /home/scan/new/ --no_label_guessing; date
Mo 5. Feb 14:28:12 CET 2018
Work directory: file:///mnt/dokumente/paperwork
Files ['file:///home/scan/new']: Importer = Import each PDF in the folder as a new document
['file:///home/scan/new']:
Running OCR on 20180205_1428_13|0 ...
Running OCR on 20180205_1428_13|1 ...
Running OCR on 20180205_1428_13|2 ...
Running OCR on 20180205_1428_13|3 ...
Running OCR on 20180205_1428_13|4 ...
Running OCR on 20180205_1428_13|5 ...
Running OCR on 20180205_1428_13|6 ...
Running OCR on 20180205_1428_13|7 ...
Running OCR on 20180205_1428_13|8 ...
Running OCR on 20180205_1428_13|9 ...
Running OCR on 20180205_1428_13|10 ...
Running OCR on 20180205_1428_13|11 ...
Running OCR on 20180205_1428_13|12 ...
Running OCR on 20180205_1428_13|13 ...
Running OCR on 20180205_1428_13|14 ...
Running OCR on 20180205_1428_13|15 ...
Running OCR on 20180205_1428_13|16 ...
Running OCR on 20180205_1428_13|17 ...
Running OCR on 20180205_1428_13|18 ...
Running OCR on 20180205_1428_13|19 ...
Running OCR on 20180205_1428_13|20 ...
Running OCR on 20180205_1428_13|21 ...
Running OCR on 20180205_1428_13|22 ...
Running OCR on 20180205_1428_13|23 ...
Running OCR on 20180205_1428_13|24 ...
Running OCR on 20180205_1428_13|25 ...
Running OCR on 20180205_1428_13|26 ...
Running OCR on 20180205_1428_13|27 ...
Running OCR on 20180205_1428_13|28 ...
Running OCR on 20180205_1428_13|29 ...
Running OCR on 20180205_1428_13|30 ...
Running OCR on 20180205_1428_13|31 ...
Document 20180205_1428_13 (labels: )
Updating index ...
Done
{
    "guessed_labels": [],
    "imports": {
        "imported_file_uris": [
            "file:///home/scan/new/20180204_124315_000652.pdf"
        ],
        "new_docs": [
            {
                "docid": "20180205_1428_13",
                "labels": []
            }
        ],
        "new_docs_pages": [
            "20180205_1428_13|0",
            "20180205_1428_13|1",
            "20180205_1428_13|2",
            "20180205_1428_13|3",
            "20180205_1428_13|4",
            "20180205_1428_13|5",
            "20180205_1428_13|6",
            "20180205_1428_13|7",
            "20180205_1428_13|8",
            "20180205_1428_13|9",
            "20180205_1428_13|10",
            "20180205_1428_13|11",
            "20180205_1428_13|12",
            "20180205_1428_13|13",
            "20180205_1428_13|14",
            "20180205_1428_13|15",
            "20180205_1428_13|16",
            "20180205_1428_13|17",
            "20180205_1428_13|18",
            "20180205_1428_13|19",
            "20180205_1428_13|20",
            "20180205_1428_13|21",
            "20180205_1428_13|22",
            "20180205_1428_13|23",
            "20180205_1428_13|24",
            "20180205_1428_13|25",
            "20180205_1428_13|26",
            "20180205_1428_13|27",
            "20180205_1428_13|28",
            "20180205_1428_13|29",
            "20180205_1428_13|30",
            "20180205_1428_13|31"
        ],
        "stats": {
            "Document(s)": 1,
            "Image file(s)": 0,
            "PDF": 1,
            "Page(s)": 32
        },
        "upd_docs": [],
        "upd_docs_pages": []
    },
    "ocr": [
        "20180205_1428_13|0",
        "20180205_1428_13|3",
        "20180205_1428_13|1",
        "20180205_1428_13|2",
        "20180205_1428_13|4",
        "20180205_1428_13|7",
        "20180205_1428_13|5",
        "20180205_1428_13|8",
        "20180205_1428_13|9",
        "20180205_1428_13|10",
        "20180205_1428_13|12",
        "20180205_1428_13|11",
        "20180205_1428_13|13",
        "20180205_1428_13|14",
        "20180205_1428_13|15",
        "20180205_1428_13|16",
        "20180205_1428_13|18",
        "20180205_1428_13|19",
        "20180205_1428_13|17",
        "20180205_1428_13|20",
        "20180205_1428_13|21",
        "20180205_1428_13|22",
        "20180205_1428_13|23",
        "20180205_1428_13|25",
        "20180205_1428_13|24",
        "20180205_1428_13|26",
        "20180205_1428_13|28",
        "20180205_1428_13|6",
        "20180205_1428_13|29",
        "20180205_1428_13|30",
        "20180205_1428_13|31",
        "20180205_1428_13|27"
    ],
    "status": "ok"
}

real    3m35,234s
user    10m29,352s
sys     0m8,363s
Mo 5. Feb 14:31:47 CET 2018
```

## OCR on fresh imported document without OCR with 4 threads on dualcore CPU with HT
**194 seconds**
```
[toerb@mittagspause ~]$ date ;time paperwork-shell ocr 20180205_1438_40; date
Mo 5. Feb 14:38:51 CET 2018
Work directory: file:///mnt/dokumente/paperwork
Running OCR on 20180205_1438_40|0 ...
Running OCR on 20180205_1438_40|9 ...
Running OCR on 20180205_1438_40|12 ...
Running OCR on 20180205_1438_40|14 ...
Running OCR on 20180205_1438_40|6 ...
Running OCR on 20180205_1438_40|20 ...
Running OCR on 20180205_1438_40|21 ...
Running OCR on 20180205_1438_40|15 ...
Running OCR on 20180205_1438_40|3 ...
Running OCR on 20180205_1438_40|10 ...
Running OCR on 20180205_1438_40|19 ...
Running OCR on 20180205_1438_40|1 ...
Running OCR on 20180205_1438_40|24 ...
Running OCR on 20180205_1438_40|28 ...
Running OCR on 20180205_1438_40|17 ...
Running OCR on 20180205_1438_40|31 ...
Running OCR on 20180205_1438_40|7 ...
Running OCR on 20180205_1438_40|13 ...
Running OCR on 20180205_1438_40|25 ...
Running OCR on 20180205_1438_40|2 ...
Running OCR on 20180205_1438_40|18 ...
Running OCR on 20180205_1438_40|4 ...
Running OCR on 20180205_1438_40|26 ...
Running OCR on 20180205_1438_40|8 ...
Running OCR on 20180205_1438_40|29 ...
Running OCR on 20180205_1438_40|11 ...
Running OCR on 20180205_1438_40|27 ...
Running OCR on 20180205_1438_40|23 ...
Running OCR on 20180205_1438_40|16 ...
Running OCR on 20180205_1438_40|5 ...
Running OCR on 20180205_1438_40|22 ...
Running OCR on 20180205_1438_40|30 ...
Updating index ...
Done
{
    "ocr": [
        "20180205_1438_40|0",
        "20180205_1438_40|9",
        "20180205_1438_40|14",
        "20180205_1438_40|12",
        "20180205_1438_40|20",
        "20180205_1438_40|21",
        "20180205_1438_40|15",
        "20180205_1438_40|3",
        "20180205_1438_40|10",
        "20180205_1438_40|19",
        "20180205_1438_40|1",
        "20180205_1438_40|28",
        "20180205_1438_40|24",
        "20180205_1438_40|31",
        "20180205_1438_40|17",
        "20180205_1438_40|7",
        "20180205_1438_40|13",
        "20180205_1438_40|25",
        "20180205_1438_40|2",
        "20180205_1438_40|18",
        "20180205_1438_40|4",
        "20180205_1438_40|8",
        "20180205_1438_40|29",
        "20180205_1438_40|26",
        "20180205_1438_40|11",
        "20180205_1438_40|23",
        "20180205_1438_40|6",
        "20180205_1438_40|16",
        "20180205_1438_40|5",
        "20180205_1438_40|22",
        "20180205_1438_40|30",
        "20180205_1438_40|27"
    ],
    "status": "ok"
}

real    3m14,140s
user    10m21,985s
sys     0m7,761s
Mo 5. Feb 14:42:05 CET 2018
```

**Comment by toerb** [comment]
@jflesch what is the state of multithreaded ocr in paperwork-gui?
I see `JobOCR.do_ocr_with_custom_heuristic()` where threading is used but not in `JobOCR.do_ocr_with_tool_heuristic()`.
When importing a PDF in the frontend my installation the ocr is singlethreaded.

**Comment by jflesch** [comment]
`JobOCR.do_ocr_with_tool_heuristic()` use the orientation detection functions of the OCR tool (Tesseract).

`JobOCR.do_ocr_with_custom_heuristic()` is used when the OCR tool doesn't provide page orientation detection functions (Cuneiform and old versions of Tesseract). It runs the OCR tool on the 4 possible orientations and use an heuristic function to give a score to each one (based on the number of words found). It keeps the orientation that gave the best score. --> trying on the 4 possible orientations is done in parallel in one shot (on a 4 cores CPU)

**Comment by jflesch** [comment]
In other words, `JobOCR.do_ocr_with_custom_heuristic()`  is old way of doing things. It's pretty much obsolete at this point.

**Comment by toerb** [comment]
So all effort for further parallelization should be directed to `JobOCR.do_ocr_with_custom_heuristic()`?
I can have a look tomorrow if there can be a similar implementation like in the paperwork-shell.

**Comment by jflesch** [comment]
No. As I said, `JobOCR.do_ocr_with_custom_heuristic()` is about to become obsolete.
You would better focus on `JobOCR.do_ocr_with_tool_heuristic()`.

**Comment by toerb** [comment]
Oh yes sorry. I mixed them up.

**Comment by jflesch** [comment]
Anyway, if you want to parallelize OCR in the GUI, you will have one major difficulty: Paperwork displays the OCR as it goes. This won't be an easy change :/

**Comment by toerb** [comment]
Ohh I see what you mean with your last sentence.
I think this change would be too complex for what spare time I have in the coming weeks.

My use case for fast ocr using cron jobs or `inotify` is fulfilled with the merged change in `paperwork-backend`.
Can you take the needed GUI changes for multithreaded ocr in your timeline? I think this would go nicely hand in hand with some other planned GUI changes.
If I have more spare time in march I can have a look again on the needed changes.

Are you planning to release 1.2.4 in the coming days with the ocr changes in `paperwork-shell`?
Thank you for your time so far!

**Comment by jflesch** [comment]
> Can you take the needed GUI changes for multithreaded ocr in your timeline?

(@Jflesch looks at [his TODO list](https://github.com/openpaperwork/paperwork/issues) and sighs).

No, not really. My goal at the moment are #702 and then #194 and they are going to require a *lot* of time.

> Are you planning to release 1.2.4 in the coming days with the ocr changes in paperwork-shell?

Usually new features go into the next minor version (1.3.x here), not the next update (1.2.4 ; usually bug fixes only).
However, because of #702 , 1.3.x won't be released any time soon (I would estimate it at about 6 months to 1 year).

That's why I made [continuous Flatpak builds of the branch 'master' and 'develop'](https://github.com/openpaperwork/paperwork/blob/master/flatpak/README.markdown): So people can work with the latest features (and latest bugs ;) without waiting for the latest release.

I would prefer you use the Flatpak build if possible.
If not, since your changes are small, I guess I could include them in 1.2.4 ...

**Comment by toerb** [comment]
> No, not really. My goals at the moment are #702 and then #194 and they are going to require a lot of time.

You're right. This is enough work for some time and #194 also will change a lot in the GUI I think.

> I would prefer you use the Flatpak build if possible.
> If not possible, since your changes are small, I guess I could include them in 1.2.4 ...

Out of personal preference I am not going to use flatpak but I am okay with manually patching my local installations with these changes.
