### ISSUE TITLE
Drag'n'drop inside a document is broken

### ISSUE THREAD

**Issue by jflesch** [jflesch/paperwork#502]
Drag'n'drop inside a document is broken

**Comment by jflesch** [comment]
```
AttributeError: 'PageDropHandler' object has no attribute 'visible'
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/paperwork-1.0-py3.5.egg/paperwork/frontend/mainwindow/pages.py", line 1563, in _on_drag_motion
  File "/usr/local/lib/python3.5/dist-packages/paperwork-1.0-py3.5.egg/paperwork/frontend/util/canvas/drawers.py", line 180, in redraw
AttributeError: 'PageDropHandler' object has no attribute 'visible'
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/paperwork-1.0-py3.5.egg/paperwork/frontend/mainwindow/pages.py", line 1607, in _on_drag_leave
  File "/usr/local/lib/python3.5/dist-packages/paperwork-1.0-py3.5.egg/paperwork/frontend/util/canvas/drawers.py", line 180, in redraw
AttributeError: 'PageDropHandler' object has no attribute 'visible'
```

**Comment by jflesch** [comment]
6986632f8313136dda9f1e3f049d8815bb41303d
