### ISSUE TITLE
"Redo OCR on all documents" is broken

### ISSUE THREAD

**Issue by jflesch** [jflesch/paperwork#503]
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/paperwork-1.0-py3.5.egg/paperwork/frontend/util/actions.py", line 97, in on_action_activated_cb
  File "/usr/local/lib/python3.5/dist-packages/paperwork-1.0-py3.5.egg/paperwork/frontend/util/actions.py", line 64, in __do
  File "/usr/local/lib/python3.5/dist-packages/paperwork-1.0-py3.5.egg/paperwork/frontend/mainwindow/__init__.py", line 1580, in do
  File "/usr/local/lib/python3.5/dist-packages/paperwork-1.0-py3.5.egg/paperwork/frontend/mainwindow/__init__.py", line 1556, in __init__
AttributeError: 'list_iterator' object has no attribute 'next'
```

**Comment by jflesch** [comment]
03c778ec3c2119ec2e319a095db698aae31e221e
