### ISSUE TITLE
Ctrl+PageDown / Ctrl+PageUp broken

### ISSUE THREAD

**Issue by jflesch** [jflesch/paperwork#505]
Ctrl+PageDown / Ctrl+PageUp broken

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/paperwork-1.0-py3.5.egg/paperwork/frontend/mainwindow/__init__.py", line 3286, in __on_key_press_event_cb
  File "/usr/local/lib/python3.5/dist-packages/paperwork-1.0-py3.5.egg/paperwork/frontend/mainwindow/docs.py", line 1012, in select_doc
AttributeError: 'NoneType' object has no attribute 'get_index'
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/paperwork-1.0-py3.5.egg/paperwork/frontend/mainwindow/__init__.py", line 3286, in __on_key_press_event_cb
  File "/usr/local/lib/python3.5/dist-packages/paperwork-1.0-py3.5.egg/paperwork/frontend/mainwindow/docs.py", line 1012, in select_doc
AttributeError: 'NoneType' object has no attribute 'get_index'
```

**Comment by jflesch** [comment]
Actually, it works fine on a GNU/Linux Debian stable

**Comment by jflesch** [comment]
d2ab7c74e118a902a98fefce9e2b9069e199abfe
