### ISSUE TITLE
Network scanner

### ISSUE THREAD

**Issue by Dev-Crea** [jflesch/paperwork#542]
Hello.

I have a scanner plugged into my networks but it does not appear on the list of devices.

It is configured with xsane and works very well with GIMP.

How to configure paperwork to find it in the list of devices?

**Comment by jflesch** [comment]
If GIMP sees it, Paperwork should too (they use the same library).

After opening the settings of Paperwork, can you open the diagnostic dialog and send me the output please ? (either on this ticket, or by mail at jflesch@openpaper.work ).
(If you're using Gnome, the application menu will be at the top of the screen)

**Comment by jflesch** [comment]
Sorry, I forgot : Instructions to access the diagnostic dialog can be found here : https://openpaper.work/helpdesk/kb/1/

**Comment by Dev-Crea** [comment]
```linux
INFO   paperwork.paperwork            Using locales in '/usr/share/locale'
INFO   pyinsane2.sane.abstract_proc   Starting Pyinsane subprocess
INFO   pyinsane2.sane.abstract_proc   Pyinsane pipes: /tmp/pyinsane_hg3n2l3d/pipe_c2s | /tmp/pyinsane_hg3n2l3d/pipe_s2c
INFO   pyinsane2.sane.abstract_proc   Connected to Pyinsane subprocess
INFO   paperwork_backend.config       Config file found: /home/jeremy/.config/paperwork.conf
INFO   paperwork_backend.config       Reloading /home/jeremy/.config/paperwork.conf ...
INFO   paperwork.frontend.util        UI file used: /usr/share/paperwork/mainwindow/appmenu.xml
INFO   paperwork.frontend.util        CSS file used: /usr/share/paperwork/application.css
INFO   paperwork.frontend.util        UI file used: /usr/share/paperwork/mainwindow/mainwindow.glade
WARNING paperwork.frontend.util.canvas Ignore useless call to redraw()
INFO   paperwork.frontend.util.jobs   [Scheduler Main] Starting
INFO   paperwork.frontend.util.jobs   [Scheduler Main] Started
INFO   paperwork.frontend.util.jobs   [Scheduler Scan] Starting
INFO   paperwork.frontend.util.jobs   [Scheduler Scan] Started
INFO   paperwork.frontend.util.jobs   [Scheduler OCR] Starting
INFO   paperwork.frontend.util.jobs   [Scheduler OCR] Started
INFO   paperwork.frontend.util.jobs   [Scheduler Page boxes loader] Starting
INFO   paperwork.frontend.util.jobs   [Scheduler Page boxes loader] Started
INFO   paperwork.frontend.util.jobs   [Scheduler Index search / update] Starting
INFO   paperwork.frontend.util.jobs   [Scheduler Index search / update] Started
INFO   paperwork.frontend.util.jobs   [Scheduler Progress] Starting
INFO   paperwork.frontend.util.jobs   [Scheduler Progress] Started
INFO   paperwork.frontend.util.actions Action: [Refresh index]
INFO   paperwork_backend.docsearch    Opening index dir '/home/jeremy/.local/share/paperwork/index' ...
INFO   paperwork.frontend.util.canvas Animators: 1
WARNING paperwork.frontend.util.canvas Ignore useless call to redraw()
WARNING paperwork_backend.docsearch    Warning: unknown doc type for doc 'Diplome - CDI.png'
WARNING paperwork_backend.docsearch    Warning: unknown doc type for doc 'Carte d'identite.png'
WARNING paperwork_backend.docsearch    Warning: unknown doc type for doc 'Carte d'identite.pdf'
WARNING paperwork_backend.docsearch    Warning: unknown doc type for doc 'Diplome - CDI.xcf'
WARNING paperwork_backend.docsearch    Warning: unknown doc type for doc 'Diplome - CDI.pdf'
WARNING paperwork_backend.docsearch    Warning: unknown doc type for doc 'Carte d'identite.xcf'
INFO   paperwork.frontend.mainwindow  Image view port resized. (0, 0) --> (827, 966)
INFO   paperwork.frontend.mainwindow  Changing zoom level (internal): True/1.0
INFO   paperwork.frontend.util.actions Action: [Set document date]
INFO   paperwork.frontend.mainwindow.docs Invalid date: New document
INFO   paperwork.frontend.mainwindow  Document examen finished. Updating index ...
INFO   paperwork.frontend.mainwindow  0 labels found
INFO   paperwork.frontend.mainwindow  New document: 0
INFO   paperwork.frontend.mainwindow  Updated document: 0
INFO   paperwork.frontend.mainwindow  Deleted document: 0
INFO   paperwork.frontend.mainwindow  No changes
INFO   paperwork.frontend.util.canvas Animators: 0
INFO   paperwork.frontend.util.canvas Animators: 1
WARNING paperwork.frontend.util.canvas Ignore useless call to redraw()
INFO   paperwork.frontend.mainwindow  Searching: []
INFO   paperwork.frontend.mainwindow  Got 0 documents
INFO   paperwork.frontend.util.canvas Animators: 0
INFO   paperwork.frontend.mainwindow  Got 0 suggestions
INFO   paperwork.frontend.util.actions Action: [Open settings dialog]
INFO   paperwork.frontend.util        UI file used: /usr/share/paperwork/settingswindow/settingswindow.glade
INFO   paperwork.frontend.settingswindow Distribution: [arch]
WARNING paperwork_backend.util         Unknown language [osd]
INFO   paperwork.frontend.util.jobs   [Scheduler progress] Starting
INFO   paperwork.frontend.util.jobs   [Scheduler progress] Started
INFO   paperwork.frontend.settingswindow Looking for scan devices ...
INFO   paperwork.frontend.settingswindow Device found: [Noname UVC Camera (046d:0821)] -> [v4l:/dev/video0]
INFO   paperwork.frontend.settingswindow End of scan for device
INFO   paperwork.frontend.settingswindow Got value [['Noname UVC Camera (046d:0821)', 'v4l:/dev/video0']]
WARNING paperwork.frontend.util.jobs   Job DeviceFinder:0 took 8951ms and is unstoppable ! (maximum allowed: 500ms)
INFO   paperwork.frontend.settingswindow Selected scanner: 0
INFO   paperwork.frontend.settingswindow Looking for sources of device [v4l:/dev/video0]
INFO   paperwork.frontend.settingswindow Sources found: []
INFO   paperwork.frontend.settingswindow Got all the sources
INFO   paperwork.frontend.settingswindow Looking for resolution of device [v4l:/dev/video0]
INFO   paperwork.frontend.settingswindow Selected source: -1
WARNING paperwork.frontend.settingswindow No possible resolutions specified. Assuming default
INFO   paperwork.frontend.settingswindow Got all the resolutions
INFO   paperwork.frontend.settingswindow Scanner sources: []
INFO   paperwork.frontend.settingswindow Got value [['75', 75]]
INFO   paperwork.frontend.settingswindow Got value [['100', 100]]
INFO   paperwork.frontend.settingswindow Got value [['150', 150]]
INFO   paperwork.frontend.settingswindow Got value [['200', 200]]
INFO   paperwork.frontend.settingswindow Got value [['300 (recommandée)', 300]]
INFO   paperwork.frontend.settingswindow Got value [['600', 600]]
INFO   paperwork.frontend.settingswindow Got value [['1200', 1200]]
INFO   paperwork_backend.config       Updating /home/jeremy/.config/paperwork.conf ...
INFO   paperwork_backend.config       Done
INFO   paperwork.frontend.settingswindow Settings window destroyed
INFO   paperwork.frontend.util.jobs   [Scheduler progress] Stopping
INFO   paperwork.frontend.util.jobs   [Scheduler progress] Stopped
INFO   paperwork.frontend.util.actions Action: [Opening diagnostic dialog]
INFO   paperwork.frontend.util        UI file used: /usr/share/paperwork/diag/diagdialog.glade
INFO   paperwork.frontend.diag        ====== START OF SYSTEM INFO ======
INFO   paperwork.frontend.diag        os.name: posix
INFO   paperwork.frontend.diag        sys.version: 3.5.2 (default, Nov  7 2016, 11:31:36) 
[GCC 6.2.1 20160830]
INFO   paperwork.frontend.diag        os.uname: posix.uname_result(sysname='Linux', nodename='******', release='4.8.10-1-ARCH', version='#1 SMP PREEMPT Mon Nov 21 11:55:43 CET 2016', machine='x86_64')
INFO   paperwork.frontend.diag        platform.architecture: ('64bit', 'ELF')
INFO   paperwork.frontend.diag        platform.platform: Linux-4.8.10-1-ARCH-x86_64-with-arch-Arch-Linux
INFO   paperwork.frontend.diag        platform.processor: 
INFO   paperwork.frontend.diag        platform.version: #1 SMP PREEMPT Mon Nov 21 11:55:43 CET 2016
INFO   paperwork.frontend.diag        platform.linux_distribution: ('arch', 'Arch', 'Linux')
INFO   paperwork.frontend.diag        platform.win32_ver: ('', '', '', '')
INFO   paperwork.frontend.diag        multiprocessing.cpu_count: 8
INFO   paperwork.frontend.diag        Available memory: 16777949184
INFO   paperwork.frontend.diag        ====== END OF SYSTEM INFO ======
INFO   paperwork.frontend.diag        ====== START OF PAPERWORK INFO ======
INFO   paperwork.frontend.diag        Paperwork version: 1.0.5
INFO   paperwork.frontend.diag        Total number of documents: 0
INFO   paperwork.frontend.diag        Document types: {}
INFO   paperwork.frontend.diag        Total number of pages: 0 (average: -0.0/doc)
INFO   paperwork.frontend.diag        Maximum number of pages in one document: 0
INFO   paperwork.frontend.diag        Total number of words: 0 (average: -0.0/page)
INFO   paperwork.frontend.diag        Average word length: -0.0
INFO   paperwork.frontend.diag        Max word length: 0
INFO   paperwork.frontend.diag        ====== END OF PAPERWORK INFO ======
INFO   paperwork.frontend.diag        ====== START OF SCANNER INFO ======
INFO   paperwork.frontend.diag        1 scanners found
INFO   paperwork.frontend.diag        === 'v4l:/dev/video0' (Noname, UVC Camera (046d:0821), virtual device) ===
INFO   paperwork.frontend.diag        Option: mode
INFO   paperwork.frontend.diag          Title: Scan mode
INFO   paperwork.frontend.diag          Desc: Selects the scan mode (e.g., lineart, monochrome, or color).
INFO   paperwork.frontend.diag          Type: <class 'pyinsane2.sane.rawapi.SaneValueType'> : String (3)
INFO   paperwork.frontend.diag          Unit: <class 'pyinsane2.sane.rawapi.SaneUnit'> : None (0)
INFO   paperwork.frontend.diag          Size: 6
INFO   paperwork.frontend.diag          Capabilities: <class 'pyinsane2.sane.rawapi.SaneCapabilities'> :[ Soft_select, Soft_detect,]
INFO   paperwork.frontend.diag          Constraint type: <class 'pyinsane2.sane.rawapi.SaneConstraintType'> : String list (3)
INFO   paperwork.frontend.diag          Constraint: ['Gray', 'Color']
INFO   paperwork.frontend.diag          Value: Gray
INFO   paperwork.frontend.diag        Option: br-y
INFO   paperwork.frontend.diag          Title: Bottom-right y
INFO   paperwork.frontend.diag          Desc: Bottom-right y position of scan area.
INFO   paperwork.frontend.diag          Type: <class 'pyinsane2.sane.rawapi.SaneValueType'> : Integer (1)
INFO   paperwork.frontend.diag          Unit: <class 'pyinsane2.sane.rawapi.SaneUnit'> : Pixel (1)
INFO   paperwork.frontend.diag          Size: 4
INFO   paperwork.frontend.diag          Capabilities: <class 'pyinsane2.sane.rawapi.SaneCapabilities'> :[ Soft_select, Soft_detect, Inactive,]
INFO   paperwork.frontend.diag          Constraint type: <class 'pyinsane2.sane.rawapi.SaneConstraintType'> : Range (1)
INFO   paperwork.frontend.diag          Constraint: (120, 511, 1)
WARNING paperwork.frontend.diag            Value: *FAILED*
ERROR  paperwork.frontend.diag        <class 'pyinsane2.sane.rawapi.SaneStatus'> : Data is invalid (4)
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/paperwork/frontend/diag/__init__.py", line 168, in _get_scanner_info
    logger.info("  Value: {}".format(str(opt.value)))
  File "/usr/lib/python3.5/site-packages/pyinsane2/sane/abstract_proc.py", line 160, in _get_value
    return remote_do('get_option_value', self._scanner_name, self.name)
  File "/usr/lib/python3.5/site-packages/pyinsane2/sane/abstract_proc.py", line 74, in remote_do
    raise exc_class(*result['exception_args'])
pyinsane2.sane.rawapi.SaneException: <class 'pyinsane2.sane.rawapi.SaneStatus'> : Data is invalid (4)
INFO   paperwork.frontend.diag        Option: br-x
INFO   paperwork.frontend.diag          Title: Bottom-right x
INFO   paperwork.frontend.diag          Desc: Bottom-right x position of scan area.
INFO   paperwork.frontend.diag          Type: <class 'pyinsane2.sane.rawapi.SaneValueType'> : Integer (1)
INFO   paperwork.frontend.diag          Unit: <class 'pyinsane2.sane.rawapi.SaneUnit'> : Pixel (1)
INFO   paperwork.frontend.diag          Size: 4
INFO   paperwork.frontend.diag          Capabilities: <class 'pyinsane2.sane.rawapi.SaneCapabilities'> :[ Soft_select, Soft_detect, Inactive,]
INFO   paperwork.frontend.diag          Constraint type: <class 'pyinsane2.sane.rawapi.SaneConstraintType'> : Range (1)
INFO   paperwork.frontend.diag          Constraint: (160, 767, 1)
WARNING paperwork.frontend.diag            Value: *FAILED*
ERROR  paperwork.frontend.diag        <class 'pyinsane2.sane.rawapi.SaneStatus'> : Data is invalid (4)
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/paperwork/frontend/diag/__init__.py", line 168, in _get_scanner_info
    logger.info("  Value: {}".format(str(opt.value)))
  File "/usr/lib/python3.5/site-packages/pyinsane2/sane/abstract_proc.py", line 160, in _get_value
    return remote_do('get_option_value', self._scanner_name, self.name)
  File "/usr/lib/python3.5/site-packages/pyinsane2/sane/abstract_proc.py", line 74, in remote_do
    raise exc_class(*result['exception_args'])
pyinsane2.sane.rawapi.SaneException: <class 'pyinsane2.sane.rawapi.SaneStatus'> : Data is invalid (4)
INFO   paperwork.frontend.diag        Option: contrast
INFO   paperwork.frontend.diag          Title: Contrast
INFO   paperwork.frontend.diag          Desc: Controls the contrast of the acquired image.
INFO   paperwork.frontend.diag          Type: <class 'pyinsane2.sane.rawapi.SaneValueType'> : Integer (1)
INFO   paperwork.frontend.diag          Unit: <class 'pyinsane2.sane.rawapi.SaneUnit'> : None (0)
INFO   paperwork.frontend.diag          Size: 4
INFO   paperwork.frontend.diag          Capabilities: <class 'pyinsane2.sane.rawapi.SaneCapabilities'> :[ Soft_select, Soft_detect,]
INFO   paperwork.frontend.diag          Constraint type: <class 'pyinsane2.sane.rawapi.SaneConstraintType'> : Range (1)
INFO   paperwork.frontend.diag          Constraint: (0, 255, 0)
INFO   paperwork.frontend.diag          Value: 32
INFO   paperwork.frontend.diag        Option: white-level
INFO   paperwork.frontend.diag          Title: White level
INFO   paperwork.frontend.diag          Desc: Selects what radiance level should be considered "white".
INFO   paperwork.frontend.diag          Type: <class 'pyinsane2.sane.rawapi.SaneValueType'> : Integer (1)
INFO   paperwork.frontend.diag          Unit: <class 'pyinsane2.sane.rawapi.SaneUnit'> : None (0)
INFO   paperwork.frontend.diag          Size: 4
INFO   paperwork.frontend.diag          Capabilities: <class 'pyinsane2.sane.rawapi.SaneCapabilities'> :[ Soft_select, Soft_detect,]
INFO   paperwork.frontend.diag          Constraint type: <class 'pyinsane2.sane.rawapi.SaneConstraintType'> : Range (1)
INFO   paperwork.frontend.diag          Constraint: (0, 255, 0)
INFO   paperwork.frontend.diag          Value: 0
INFO   paperwork.frontend.diag        Option: color
INFO   paperwork.frontend.diag          Title: Picture color
INFO   paperwork.frontend.diag          Desc: Sets the picture's color.
INFO   paperwork.frontend.diag          Type: <class 'pyinsane2.sane.rawapi.SaneValueType'> : Integer (1)
INFO   paperwork.frontend.diag          Unit: <class 'pyinsane2.sane.rawapi.SaneUnit'> : None (0)
INFO   paperwork.frontend.diag          Size: 4
INFO   paperwork.frontend.diag          Capabilities: <class 'pyinsane2.sane.rawapi.SaneCapabilities'> :[ Soft_select, Soft_detect,]
INFO   paperwork.frontend.diag          Constraint type: <class 'pyinsane2.sane.rawapi.SaneConstraintType'> : Range (1)
INFO   paperwork.frontend.diag          Constraint: (0, 255, 0)
INFO   paperwork.frontend.diag          Value: 32
INFO   paperwork.frontend.diag        Option: hue
INFO   paperwork.frontend.diag          Title: Hue
INFO   paperwork.frontend.diag          Desc: Controls the "hue" (blue-level) of the acquired image.
INFO   paperwork.frontend.diag          Type: <class 'pyinsane2.sane.rawapi.SaneValueType'> : Integer (1)
INFO   paperwork.frontend.diag          Unit: <class 'pyinsane2.sane.rawapi.SaneUnit'> : None (0)
INFO   paperwork.frontend.diag          Size: 4
INFO   paperwork.frontend.diag          Capabilities: <class 'pyinsane2.sane.rawapi.SaneCapabilities'> :[ Soft_select, Soft_detect,]
INFO   paperwork.frontend.diag          Constraint type: <class 'pyinsane2.sane.rawapi.SaneConstraintType'> : Range (1)
INFO   paperwork.frontend.diag          Constraint: (0, 255, 0)
INFO   paperwork.frontend.diag          Value: 0
INFO   paperwork.frontend.diag        Option: tl-y
INFO   paperwork.frontend.diag          Title: Top-left y
INFO   paperwork.frontend.diag          Desc: Top-left y position of scan area.
INFO   paperwork.frontend.diag          Type: <class 'pyinsane2.sane.rawapi.SaneValueType'> : Integer (1)
INFO   paperwork.frontend.diag          Unit: <class 'pyinsane2.sane.rawapi.SaneUnit'> : Pixel (1)
INFO   paperwork.frontend.diag          Size: 4
INFO   paperwork.frontend.diag          Capabilities: <class 'pyinsane2.sane.rawapi.SaneCapabilities'> :[ Soft_select, Soft_detect, Inactive,]
INFO   paperwork.frontend.diag          Constraint type: <class 'pyinsane2.sane.rawapi.SaneConstraintType'> : Range (1)
INFO   paperwork.frontend.diag          Constraint: (0, 391, 1)
WARNING paperwork.frontend.diag            Value: *FAILED*
ERROR  paperwork.frontend.diag        <class 'pyinsane2.sane.rawapi.SaneStatus'> : Data is invalid (4)
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/paperwork/frontend/diag/__init__.py", line 168, in _get_scanner_info
    logger.info("  Value: {}".format(str(opt.value)))
  File "/usr/lib/python3.5/site-packages/pyinsane2/sane/abstract_proc.py", line 160, in _get_value
    return remote_do('get_option_value', self._scanner_name, self.name)
  File "/usr/lib/python3.5/site-packages/pyinsane2/sane/abstract_proc.py", line 74, in remote_do
    raise exc_class(*result['exception_args'])
pyinsane2.sane.rawapi.SaneException: <class 'pyinsane2.sane.rawapi.SaneStatus'> : Data is invalid (4)
INFO   paperwork.frontend.diag        Option: brightness
INFO   paperwork.frontend.diag          Title: Brightness
INFO   paperwork.frontend.diag          Desc: Controls the brightness of the acquired image.
INFO   paperwork.frontend.diag          Type: <class 'pyinsane2.sane.rawapi.SaneValueType'> : Integer (1)
INFO   paperwork.frontend.diag          Unit: <class 'pyinsane2.sane.rawapi.SaneUnit'> : None (0)
INFO   paperwork.frontend.diag          Size: 4
INFO   paperwork.frontend.diag          Capabilities: <class 'pyinsane2.sane.rawapi.SaneCapabilities'> :[ Soft_select, Soft_detect,]
INFO   paperwork.frontend.diag          Constraint type: <class 'pyinsane2.sane.rawapi.SaneConstraintType'> : Range (1)
INFO   paperwork.frontend.diag          Constraint: (0, 255, 0)
INFO   paperwork.frontend.diag          Value: 128
INFO   paperwork.frontend.diag        Option: channel
INFO   paperwork.frontend.diag          Title: Channel
INFO   paperwork.frontend.diag          Desc: Selects the channel of the v4l device (e.g. television or video-in.
INFO   paperwork.frontend.diag          Type: <class 'pyinsane2.sane.rawapi.SaneValueType'> : String (3)
INFO   paperwork.frontend.diag          Unit: <class 'pyinsane2.sane.rawapi.SaneUnit'> : None (0)
INFO   paperwork.frontend.diag          Size: 9
INFO   paperwork.frontend.diag          Capabilities: <class 'pyinsane2.sane.rawapi.SaneCapabilities'> :[ Soft_select, Soft_detect, Inactive,]
INFO   paperwork.frontend.diag          Constraint type: <class 'pyinsane2.sane.rawapi.SaneConstraintType'> : String list (3)
INFO   paperwork.frontend.diag          Constraint: ['Camera 1']
WARNING paperwork.frontend.diag            Value: *FAILED*
ERROR  paperwork.frontend.diag        <class 'pyinsane2.sane.rawapi.SaneStatus'> : Data is invalid (4)
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/paperwork/frontend/diag/__init__.py", line 168, in _get_scanner_info
    logger.info("  Value: {}".format(str(opt.value)))
  File "/usr/lib/python3.5/site-packages/pyinsane2/sane/abstract_proc.py", line 160, in _get_value
    return remote_do('get_option_value', self._scanner_name, self.name)
  File "/usr/lib/python3.5/site-packages/pyinsane2/sane/abstract_proc.py", line 74, in remote_do
    raise exc_class(*result['exception_args'])
pyinsane2.sane.rawapi.SaneException: <class 'pyinsane2.sane.rawapi.SaneStatus'> : Data is invalid (4)
INFO   paperwork.frontend.diag        Option: tl-x
INFO   paperwork.frontend.diag          Title: Top-left x
INFO   paperwork.frontend.diag          Desc: Top-left x position of scan area.
INFO   paperwork.frontend.diag          Type: <class 'pyinsane2.sane.rawapi.SaneValueType'> : Integer (1)
INFO   paperwork.frontend.diag          Unit: <class 'pyinsane2.sane.rawapi.SaneUnit'> : Pixel (1)
INFO   paperwork.frontend.diag          Size: 4
INFO   paperwork.frontend.diag          Capabilities: <class 'pyinsane2.sane.rawapi.SaneCapabilities'> :[ Soft_select, Soft_detect, Inactive,]
INFO   paperwork.frontend.diag          Constraint type: <class 'pyinsane2.sane.rawapi.SaneConstraintType'> : Range (1)
INFO   paperwork.frontend.diag          Constraint: (0, 607, 1)
WARNING paperwork.frontend.diag            Value: *FAILED*
ERROR  paperwork.frontend.diag        <class 'pyinsane2.sane.rawapi.SaneStatus'> : Data is invalid (4)
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/paperwork/frontend/diag/__init__.py", line 168, in _get_scanner_info
    logger.info("  Value: {}".format(str(opt.value)))
  File "/usr/lib/python3.5/site-packages/pyinsane2/sane/abstract_proc.py", line 160, in _get_value
    return remote_do('get_option_value', self._scanner_name, self.name)
  File "/usr/lib/python3.5/site-packages/pyinsane2/sane/abstract_proc.py", line 74, in remote_do
    raise exc_class(*result['exception_args'])
pyinsane2.sane.rawapi.SaneException: <class 'pyinsane2.sane.rawapi.SaneStatus'> : Data is invalid (4)
INFO   paperwork.frontend.diag        ====== END OF SCANNER INFORMATIONS ======
```

**Comment by jflesch** [comment]
Ok, that's surprising. I was expecting the scanner to appear in the list but to cause some random bug in Paperwork .. but Sane simply doesn't report the scanner.

What scanner do you have exactly ?

**Comment by jflesch** [comment]
Also, do you use ```saned``` ?

**Comment by Dev-Crea** [comment]
My scanner is an brother DCP-9020CDW (multi-function).

Yes i use `saned` for my network scanner.

**Comment by jflesch** [comment]
Your issue is clearly confusing for me. Xsane, Gimp and Paperwork clearly uses the same library to access the scanner (libsane), and yet, Paperwork doesn't see your scanner :/

2 questions:
* I guess it also works fine with ```simple-scan``` ?
* I think I remember an old bug report (can't find it back, sorry) about issues with saned not letting some applications see scanners. Also if I remember correctly, saned is not required at all on client side. Can you give it a try without ```saned``` please ?

**Comment by jflesch** [comment]
ping ?

**Comment by Yusei** [comment]
Hi. I seem to have the same issue after updating sane to version 1.0.14-11. The scanner works with simple-scan, but paperwork says:
pyinsane2.sane.rawapi.SaneException: <class 'pyinsane2.sane.rawapi.SaneStatus'> : Data is invalid (4)

**Comment by jflesch** [comment]
@Yusei : ack

Since there has been no reply from @Dev-Crea for more than 1 month on this ticket, I'm closing it.
