### ISSUE TITLE
paperwork doesn't start after latest upgrade

### ISSUE THREAD

**Issue by trenkert** [jflesch/paperwork#545]
Terminal output

```
Traceback (most recent call last):
  File "/usr/local/bin/paperwork", line 6, in <module>
    main()
  File "/usr/local/lib/python3.5/dist-packages/paperwork/paperwork.py", line 146, in main
    main_win = MainWindow(config)
  File "/usr/local/lib/python3.5/dist-packages/paperwork/frontend/mainwindow/__init__.py", line 2154, in __init__
    self.__advanced_app_menu = self.__init_app_menu(config, self.app)
  File "/usr/local/lib/python3.5/dist-packages/paperwork/frontend/mainwindow/__init__.py", line 2685, in __init_app_menu
    menu.remove(0)
AttributeError: 'NoneType' object has no attribute 'remove'

```

**Comment by jflesch** [comment]
Yeah, it seems ```pip uninstall``` doesn't clean up as well as it should :/

Someone else who had the same problem :
https://github.com/jflesch/paperwork/issues/511#issuecomment-259628814

First part of the solution:
https://github.com/jflesch/paperwork/issues/511#issuecomment-259636878

Second part of the solution:
https://github.com/jflesch/paperwork/issues/511#issuecomment-259638688

Since it's a clear fit for your problem, I'm going to assume it solves it and close this ticket. If it does not, please comment, and I'll reopen the ticket.

**Comment by trenkert** [comment]
thanks. Removing /urs/share/paperwork and then reinstalling did the trick!
