### ISSUE TITLE
Image skew is not removed automatically

### ISSUE THREAD

**Issue by sappo** [jflesch/paperwork#557]
Hi, 
my ADF produces a little skew in my documents which is not automatically corrected by pyinsane. I figured out that pyinsane has a deskew option (https://github.com/jflesch/pyinsane/blob/bad6b45b8437f4a2f2a18476d319638022294b35/src/pyinsane2/wia/properties.cpp#L310) which paperwork doesn't use if I'm not mistaken. Also I'm not sure what the default value is.

Regards//Kevin

**Comment by jflesch** [comment]
I'm going to need more information.
First of all, are we talking about the Windows version of Paperwork or the Linux one ? (the code you pointed to is specified to Windows).
Can you also provide me with the output of the diagnostic dialog please ? It would provide a lot of informations regarding your scanner. ( https://openpaper.work/en-us/helpdesk/kb/1/ )

**Comment by sappo** [comment]
I use the linux version of paperwork. My scan have about 1° skew. Currently I use imagemagic to correct the skew manually.

Here's the output:
```
WARNING paperwork.paperwork            No suitable localization file found.
INFO   pyinsane2.sane.abstract_proc   Starting Pyinsane subprocess
INFO   pyinsane2.sane.abstract_proc   Pyinsane pipes: /tmp/pyinsane_qw4_anao/pipe_c2s | /tmp/pyinsane_qw4_anao/pipe_s2c
INFO   pyinsane2.sane.abstract_proc   Connected to Pyinsane subprocess
INFO   paperwork_backend.config       Config file found: /home/sappo/.config/paperwork.conf
INFO   paperwork_backend.config       Reloading /home/sappo/.config/paperwork.conf ...
INFO   paperwork.frontend.util        UI file used: /usr/local/lib/python3.5/dist-packages/usr/share/paperwork/mainwindow/appmenu.xml
INFO   paperwork.frontend.util        CSS file used: /usr/local/lib/python3.5/dist-packages/usr/share/paperwork/application.css
INFO   paperwork.frontend.util        UI file used: /usr/local/lib/python3.5/dist-packages/usr/share/paperwork/mainwindow/mainwindow.glade
INFO   paperwork.frontend.util.jobs   [Scheduler Scan] Starting
INFO   paperwork.frontend.util.jobs   [Scheduler Scan] Started
INFO   paperwork.frontend.util.jobs   [Scheduler Main] Starting
INFO   paperwork.frontend.util.jobs   [Scheduler Main] Started
INFO   paperwork.frontend.util.jobs   [Scheduler Progress] Starting
INFO   paperwork.frontend.util.jobs   [Scheduler Progress] Started
INFO   paperwork.frontend.util.jobs   [Scheduler Page boxes loader] Starting
INFO   paperwork.frontend.util.jobs   [Scheduler Page boxes loader] Started
INFO   paperwork.frontend.util.jobs   [Scheduler Index search / update] Starting
INFO   paperwork.frontend.util.jobs   [Scheduler Index search / update] Started
INFO   paperwork.frontend.util.jobs   [Scheduler OCR] Starting
INFO   paperwork.frontend.util.jobs   [Scheduler OCR] Started
INFO   paperwork.frontend.util.actions Action: [Refresh index]
INFO   paperwork_backend.docsearch    Opening index dir '/home/sappo/.local/share/paperwork/index' ...
INFO   paperwork.frontend.util.canvas Animators: 1
INFO   paperwork.frontend.mainwindow  Image view port resized. (0, 0) --> (1568, 956)
INFO   paperwork.frontend.mainwindow  Changing zoom level (internal): True/1.0
INFO   paperwork.frontend.util.actions Action: [Set document date]
INFO   paperwork.frontend.mainwindow.docs Invalid date: New document
INFO   paperwork.frontend.mainwindow  Image view port resized. (1568, 956) --> (1118, 758)
INFO   paperwork.frontend.mainwindow  Changing zoom level (internal): True/1.0
INFO   paperwork.frontend.util.canvas Animators: 0
INFO   paperwork.frontend.util.canvas Animators: 1
INFO   paperwork.frontend.mainwindow  Document examen finished. Updating index ...
INFO   paperwork.frontend.mainwindow  10 labels found
INFO   paperwork.frontend.mainwindow  New document: 0
INFO   paperwork.frontend.mainwindow  Updated document: 0
INFO   paperwork.frontend.mainwindow  Deleted document: 0
INFO   paperwork.frontend.mainwindow  No changes
INFO   paperwork.frontend.mainwindow  Image view port resized. (1118, 758) --> (1066, 701)
INFO   paperwork.frontend.mainwindow  Changing zoom level (internal): True/1.0
INFO   paperwork.frontend.mainwindow  Searching: []
INFO   paperwork.frontend.mainwindow  Got 9 documents
INFO   paperwork.frontend.util.canvas Animators: 0
INFO   paperwork.frontend.mainwindow  Got 0 suggestions
INFO   paperwork.frontend.mainwindow.docs Will get thumbnails for 8 documents [0-8]
INFO   paperwork.frontend.mainwindow.docs Will get thumbnails for 8 documents [0-8]
INFO   paperwork.frontend.mainwindow.docs Will get thumbnails for 3 documents [0-8]
INFO   paperwork.frontend.mainwindow.docs Will get thumbnails for 1 documents [0-8]
INFO   paperwork.frontend.mainwindow.docs Will get thumbnails for 1 documents [0-8]
INFO   paperwork.frontend.util.actions Action: [Opening diagnostic dialog]
INFO   paperwork.frontend.util        UI file used: /usr/local/lib/python3.5/dist-packages/usr/share/paperwork/diag/diagdialog.glade
INFO   paperwork.frontend.diag        ====== START OF SYSTEM INFO ======
INFO   paperwork.frontend.diag        os.name: posix
INFO   paperwork.frontend.diag        sys.version: 3.5.2 (default, Nov 17 2016, 17:05:23) 
[GCC 5.4.0 20160609]
INFO   paperwork.frontend.diag        os.uname: posix.uname_result(sysname='Linux', nodename='sappo-X230', release='4.4.0-57-generic', version='#78-Ubuntu SMP Fri Dec 9 23:50:32 UTC 2016', machine='x86_64')
INFO   paperwork.frontend.diag        platform.architecture: ('64bit', 'ELF')
INFO   paperwork.frontend.diag        platform.platform: Linux-4.4.0-57-generic-x86_64-with-Ubuntu-16.04-xenial
INFO   paperwork.frontend.diag        platform.processor: x86_64
INFO   paperwork.frontend.diag        platform.version: #78-Ubuntu SMP Fri Dec 9 23:50:32 UTC 2016
INFO   paperwork.frontend.diag        platform.linux_distribution: ('Ubuntu', '16.04', 'xenial')
INFO   paperwork.frontend.diag        platform.win32_ver: ('', '', '', '')
INFO   paperwork.frontend.diag        multiprocessing.cpu_count: 4
INFO   paperwork.frontend.diag        Available memory: 3828568064
INFO   paperwork.frontend.diag        ====== END OF SYSTEM INFO ======
INFO   paperwork.frontend.diag        ====== START OF PAPERWORK INFO ======
INFO   paperwork.frontend.diag        Paperwork version: 1.0.6
INFO   paperwork.frontend.diag        Total number of documents: 9
INFO   paperwork.frontend.diag        Document types: {"<class 'paperwork_backend.img.doc.ImgDoc'>": 7, "<class 'paperwork_backend.pdf.doc.PdfDoc'>": 0}
INFO   paperwork.frontend.diag        Total number of pages: 25 (average: 2.7777777777777777/doc)
INFO   paperwork.frontend.diag        Maximum number of pages in one document: 7
INFO   paperwork.frontend.diag        Total number of words: 6521 (average: 260.84/page)
INFO   paperwork.frontend.diag        Average word length: 6.606042018095384
INFO   paperwork.frontend.diag        Max word length: 50
INFO   paperwork.frontend.diag        ====== END OF PAPERWORK INFO ======
INFO   paperwork.frontend.diag        ====== START OF SCANNER INFO ======
INFO   paperwork.frontend.diag        1 scanners found
INFO   paperwork.frontend.diag        === 'brother4:net1;dev0' (Brother, MFC-L2700DW, MFC-L2700DW) ===
INFO   paperwork.frontend.diag        Option: brightness
INFO   paperwork.frontend.diag          Title: Brightness
INFO   paperwork.frontend.diag          Desc: Controls the brightness of the acquired image.
INFO   paperwork.frontend.diag          Type: <class 'pyinsane2.sane.rawapi.SaneValueType'> : Fixed (2)
INFO   paperwork.frontend.diag          Unit: <class 'pyinsane2.sane.rawapi.SaneUnit'> : Percent (5)
INFO   paperwork.frontend.diag          Size: 4
INFO   paperwork.frontend.diag          Capabilities: <class 'pyinsane2.sane.rawapi.SaneCapabilities'> :[ Soft_select, Soft_detect, Inactive,]
INFO   paperwork.frontend.diag          Constraint type: <class 'pyinsane2.sane.rawapi.SaneConstraintType'> : Range (1)
INFO   paperwork.frontend.diag          Constraint: (-3276800, 3276800, 65536)
WARNING paperwork.frontend.diag            Value: *FAILED*
ERROR  paperwork.frontend.diag        Option 'brightness' is not active
Traceback (most recent call last):
  File "/home/sappo/.local/lib/python3.5/site-packages/paperwork/frontend/diag/__init__.py", line 168, in _get_scanner_info
    logger.info("  Value: {}".format(str(opt.value)))
  File "/home/sappo/.local/lib/python3.5/site-packages/pyinsane2/sane/abstract_proc.py", line 160, in _get_value
    return remote_do('get_option_value', self._scanner_name, self.name)
  File "/home/sappo/.local/lib/python3.5/site-packages/pyinsane2/sane/abstract_proc.py", line 74, in remote_do
    raise exc_class(*result['exception_args'])
pyinsane2.sane.rawapi.SaneException: Option 'brightness' is not active
INFO   paperwork.frontend.diag        Option: source
INFO   paperwork.frontend.diag          Title: Scan source
INFO   paperwork.frontend.diag          Desc: Selects the scan source (such as a document-feeder).
INFO   paperwork.frontend.diag          Type: <class 'pyinsane2.sane.rawapi.SaneValueType'> : String (3)
INFO   paperwork.frontend.diag          Unit: <class 'pyinsane2.sane.rawapi.SaneUnit'> : None (0)
INFO   paperwork.frontend.diag          Size: 64
INFO   paperwork.frontend.diag          Capabilities: <class 'pyinsane2.sane.rawapi.SaneCapabilities'> :[ Soft_select, Soft_detect,]
INFO   paperwork.frontend.diag          Constraint type: <class 'pyinsane2.sane.rawapi.SaneConstraintType'> : String list (3)
INFO   paperwork.frontend.diag          Constraint: ['FlatBed', 'Automatic Document Feeder(left aligned)', 'Automatic Document Feeder(centrally aligned)']
INFO   paperwork.frontend.diag          Value: Automatic Document Feeder(left aligned)
INFO   paperwork.frontend.diag        Option: tl-x
INFO   paperwork.frontend.diag          Title: Top-left x
INFO   paperwork.frontend.diag          Desc: Top-left x position of scan area.
INFO   paperwork.frontend.diag          Type: <class 'pyinsane2.sane.rawapi.SaneValueType'> : Fixed (2)
INFO   paperwork.frontend.diag          Unit: <class 'pyinsane2.sane.rawapi.SaneUnit'> : Mm (3)
INFO   paperwork.frontend.diag          Size: 4
INFO   paperwork.frontend.diag          Capabilities: <class 'pyinsane2.sane.rawapi.SaneCapabilities'> :[ Soft_select, Soft_detect,]
INFO   paperwork.frontend.diag          Constraint type: <class 'pyinsane2.sane.rawapi.SaneConstraintType'> : Range (1)
INFO   paperwork.frontend.diag          Constraint: (0, 14149222, 6553)
INFO   paperwork.frontend.diag          Value: 0
INFO   paperwork.frontend.diag        Option: tl-y
INFO   paperwork.frontend.diag          Title: Top-left y
INFO   paperwork.frontend.diag          Desc: Top-left y position of scan area.
INFO   paperwork.frontend.diag          Type: <class 'pyinsane2.sane.rawapi.SaneValueType'> : Fixed (2)
INFO   paperwork.frontend.diag          Unit: <class 'pyinsane2.sane.rawapi.SaneUnit'> : Mm (3)
INFO   paperwork.frontend.diag          Size: 4
INFO   paperwork.frontend.diag          Capabilities: <class 'pyinsane2.sane.rawapi.SaneCapabilities'> :[ Soft_select, Soft_detect,]
INFO   paperwork.frontend.diag          Constraint type: <class 'pyinsane2.sane.rawapi.SaneConstraintType'> : Range (1)
INFO   paperwork.frontend.diag          Constraint: (0, 23304601, 6553)
INFO   paperwork.frontend.diag          Value: 0
INFO   paperwork.frontend.diag        Option: mode
INFO   paperwork.frontend.diag          Title: Scan mode
INFO   paperwork.frontend.diag          Desc: Select the scan mode
INFO   paperwork.frontend.diag          Type: <class 'pyinsane2.sane.rawapi.SaneValueType'> : String (3)
INFO   paperwork.frontend.diag          Unit: <class 'pyinsane2.sane.rawapi.SaneUnit'> : None (0)
INFO   paperwork.frontend.diag          Size: 30
INFO   paperwork.frontend.diag          Capabilities: <class 'pyinsane2.sane.rawapi.SaneCapabilities'> :[ Soft_select, Soft_detect,]
INFO   paperwork.frontend.diag          Constraint type: <class 'pyinsane2.sane.rawapi.SaneConstraintType'> : String list (3)
INFO   paperwork.frontend.diag          Constraint: ['Black & White', 'Gray[Error Diffusion]', 'True Gray', '24bit Color[Fast]']
INFO   paperwork.frontend.diag          Value: 24bit Color[Fast]
INFO   paperwork.frontend.diag        Option: resolution
INFO   paperwork.frontend.diag          Title: Scan resolution
INFO   paperwork.frontend.diag          Desc: Sets the resolution of the scanned image.
INFO   paperwork.frontend.diag          Type: <class 'pyinsane2.sane.rawapi.SaneValueType'> : Integer (1)
INFO   paperwork.frontend.diag          Unit: <class 'pyinsane2.sane.rawapi.SaneUnit'> : Dpi (4)
INFO   paperwork.frontend.diag          Size: 4
INFO   paperwork.frontend.diag          Capabilities: <class 'pyinsane2.sane.rawapi.SaneCapabilities'> :[ Soft_select, Soft_detect,]
INFO   paperwork.frontend.diag          Constraint type: <class 'pyinsane2.sane.rawapi.SaneConstraintType'> : Word list (2)
INFO   paperwork.frontend.diag          Constraint: [100, 150, 200, 300, 400, 600, 1200, 2400, 4800, 9600]
INFO   paperwork.frontend.diag          Value: 200
INFO   paperwork.frontend.diag        Option: br-x
INFO   paperwork.frontend.diag          Title: Bottom-right x
INFO   paperwork.frontend.diag          Desc: Bottom-right x position of scan area.
INFO   paperwork.frontend.diag          Type: <class 'pyinsane2.sane.rawapi.SaneValueType'> : Fixed (2)
INFO   paperwork.frontend.diag          Unit: <class 'pyinsane2.sane.rawapi.SaneUnit'> : Mm (3)
INFO   paperwork.frontend.diag          Size: 4
INFO   paperwork.frontend.diag          Capabilities: <class 'pyinsane2.sane.rawapi.SaneCapabilities'> :[ Soft_select, Soft_detect,]
INFO   paperwork.frontend.diag          Constraint type: <class 'pyinsane2.sane.rawapi.SaneConstraintType'> : Range (1)
INFO   paperwork.frontend.diag          Constraint: (0, 14149222, 6553)
INFO   paperwork.frontend.diag          Value: 14149222
INFO   paperwork.frontend.diag        Option: br-y
INFO   paperwork.frontend.diag          Title: Bottom-right y
INFO   paperwork.frontend.diag          Desc: Bottom-right y position of scan area.
INFO   paperwork.frontend.diag          Type: <class 'pyinsane2.sane.rawapi.SaneValueType'> : Fixed (2)
INFO   paperwork.frontend.diag          Unit: <class 'pyinsane2.sane.rawapi.SaneUnit'> : Mm (3)
INFO   paperwork.frontend.diag          Size: 4
INFO   paperwork.frontend.diag          Capabilities: <class 'pyinsane2.sane.rawapi.SaneCapabilities'> :[ Soft_select, Soft_detect,]
INFO   paperwork.frontend.diag          Constraint type: <class 'pyinsane2.sane.rawapi.SaneConstraintType'> : Range (1)
INFO   paperwork.frontend.diag          Constraint: (0, 23304601, 6553)
INFO   paperwork.frontend.diag          Value: 23304601
INFO   paperwork.frontend.diag        Option: contrast
INFO   paperwork.frontend.diag          Title: Contrast
INFO   paperwork.frontend.diag          Desc: Controls the contrast of the acquired image.
INFO   paperwork.frontend.diag          Type: <class 'pyinsane2.sane.rawapi.SaneValueType'> : Fixed (2)
INFO   paperwork.frontend.diag          Unit: <class 'pyinsane2.sane.rawapi.SaneUnit'> : Percent (5)
INFO   paperwork.frontend.diag          Size: 4
INFO   paperwork.frontend.diag          Capabilities: <class 'pyinsane2.sane.rawapi.SaneCapabilities'> :[ Soft_select, Soft_detect, Inactive,]
INFO   paperwork.frontend.diag          Constraint type: <class 'pyinsane2.sane.rawapi.SaneConstraintType'> : Range (1)
INFO   paperwork.frontend.diag          Constraint: (-3276800, 3276800, 65536)
WARNING paperwork.frontend.diag            Value: *FAILED*
ERROR  paperwork.frontend.diag        Option 'contrast' is not active
Traceback (most recent call last):
  File "/home/sappo/.local/lib/python3.5/site-packages/paperwork/frontend/diag/__init__.py", line 168, in _get_scanner_info
    logger.info("  Value: {}".format(str(opt.value)))
  File "/home/sappo/.local/lib/python3.5/site-packages/pyinsane2/sane/abstract_proc.py", line 160, in _get_value
    return remote_do('get_option_value', self._scanner_name, self.name)
  File "/home/sappo/.local/lib/python3.5/site-packages/pyinsane2/sane/abstract_proc.py", line 74, in remote_do
    raise exc_class(*result['exception_args'])
pyinsane2.sane.rawapi.SaneException: Option 'contrast' is not active
INFO   paperwork.frontend.diag        ====== END OF SCANNER INFORMATIONS ======
```

**Comment by jflesch** [comment]
Your scanner provides no options to automatically fix the skew.
Does ImageMagick allow to fix it automatically, or do you provide the angle yourself ?

**Comment by sappo** [comment]
No, I use a script that calculates the skew (see http://www.fmwconcepts.com/imagemagick/textdeskew/index.php)

In libpillowfight you re-implemented some unpaper algorithms. Unpaper also implements deskewing maybe this is worth a try.

Also this opencv solution might be helpful (https://gist.github.com/mweibel/bd2d6c2271e42ed97b97)

**Comment by jflesch** [comment]
> In libpillowfight you re-implemented some unpaper algorithms. Unpaper also implements deskewing maybe this is worth a try.

Good point :)

I'll see to implement this feature. However it will take some times.

**Comment by jflesch** [comment]
http://www.pyimagesearch.com/2017/02/20/text-skew-correction-opencv-python/
