### ISSUE TITLE
TypeError: normalize() argument 2 must be unicode, not str

### ISSUE THREAD

**Issue by mathieumd** [jflesch/paperwork#566]
After upgrading Paperwork to version 1.0.6, I cannot see my documents anymore!

Paperwork starts, but displays nothing except the animated gif, and "Verification... (20141222_1702_28)" in the status bar.

I tried moving away that folder (20141222_1702_28), but it doesn't change anything, except that it doesn't show the status bar anymore.

In the console it says:

```
...
INFO   paperwork.frontend.mainwindow  Searching: []
ERROR  paperwork.frontend.mainwindow  Invalid search: []
ERROR  paperwork.frontend.mainwindow  Exception was: <type 'exceptions.TypeError'>: normalize() argument 2 must be unicode, not str
ERROR  paperwork.frontend.mainwindow  normalize() argument 2 must be unicode, not str
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/paperwork/frontend/mainwindow/__init__.py", line 532, in do
    search_type=self.__search_type)
  File "/usr/local/lib/python2.7/dist-packages/paperwork_backend/docsearch.py", line 636, in find_documents
    sentence = strip_accents(sentence)
  File "/usr/local/lib/python2.7/dist-packages/paperwork_backend/util.py", line 55, in strip_accents
    (character for character in unicodedata.normalize('NFD', string)
TypeError: normalize() argument 2 must be unicode, not str
```

**Comment by jflesch** [comment]
You're using Python 2 instead of Python 3.

**Comment by mathieumd** [comment]
OK, `sudo pip3 install --upgrade paperwork` is better.

But now I lose my tags. Documents lists in the left column has them, but if I edit a document, I got no list of tags; and when going back to the documents list, this very document has lost its tags.

**Comment by jflesch** [comment]
Any Python exception visible in the terminal ? (either when you open the document, or when you switch to the tag list ?)

**Comment by mathieumd** [comment]
Not when opening/editing a document, but when starting Paperwork:

```
...
INFO   paperwork.frontend.mainwindow  Document examen finished. Updating index ...
INFO   paperwork.frontend.mainwindow  31 labels found
INFO   paperwork.frontend.mainwindow  New document: 154
INFO   paperwork.frontend.mainwindow  Updated document: 0
INFO   paperwork.frontend.mainwindow  Deleted document: 0
ERROR  paperwork.frontend.diag        === UNCATCHED EXCEPTION ===
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/paperwork/frontend/mainwindow/__init__.py", line 2145, in __on_doc_exam_en
d
    examiner.docsearch.label_list = examiner.labels
  File "/usr/local/lib/python3.5/dist-packages/paperwork_backend/docsearch.py", line 843, in __set_label_list
    self.label_guesser.load(label.name)
  File "/usr/local/lib/python3.5/dist-packages/paperwork_backend/labels.py", line 257, in load
    mkdir_p(baye_dir)
  File "/usr/local/lib/python3.5/dist-packages/paperwork_backend/util.py", line 199, in mkdir_p
    os.makedirs(path)
  File "/usr/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission non accordée: '/RojPEHe5KUzecXvMmuW2WrMJgw='
ERROR  paperwork.frontend.diag        ===========================
INFO   paperwork.frontend.mainwindow  Searching: []
INFO   paperwork.frontend.mainwindow  Got 155 documents
...
```

According to `strace`, it tries to create a directory under `/`!
```
mkdir("/RojPEHe5KUzecXvMmuW2WrMJgw=", 0777) = -1 EACCES (Permission denied)
```

**Comment by jflesch** [comment]
This one was already reported #558 .
Unfortunately, there is no Paperwork release including this fix yet.

What you can do (assuming you did install Paperwork with pip3 in a system-wide manner):

```
cd /tmp
git clone https://github.com/jflesch/paperwork-backend.git
cd paperwork-backend
git checkout stable
sudo python3 ./setup.py install
```

**Comment by mathieumd** [comment]
Thanks for your help! I applied [the patch](https://github.com/jflesch/paperwork-backend/commit/11481264cfe809a5cbf5bdf77d527f0d9a7faa6b) from #558 and it works fine.
