### ISSUE TITLE
TypeError: expected string, int found when running paperwork-shell

### ISSUE THREAD

**Issue by nodiscc** [jflesch/paperwork#577]
I have reinstalled paperwork from scratch on Debian using the most recent install instructions (https://github.com/jflesch/paperwork/commit/6e8fdb7ad4106879e2c5fe2b43d981244b382a24), and `paperwork-shell` exits with an error:

```
$ sudo aptitude install python3-stdeb python3-all-dev; for i in  pyocr pyinsane2 pypillowfight paperwork-backend paperwork; do sudo pypi-install $i; done
... (installation succeeds) ...

$ paperwork-shell chkdeps paperwork_backend
Traceback (most recent call last):
  File "/usr/bin/paperwork-shell", line 187, in <module>
    sys.exit(COMMANDS[args.cmd](*args.cmd_args))
  File "/usr/bin/paperwork-shell", line 131, in chkdeps
    _chkdeps(module_name, distribution)
  File "/usr/bin/paperwork-shell", line 78, in _chkdeps
    missing = module.find_missing_dependencies()
  File "/usr/lib/python2.7/dist-packages/paperwork_backend/deps.py", line 80, in find_missing_dependencies
    missing += check_python_version()
  File "/usr/lib/python2.7/dist-packages/paperwork_backend/deps.py", line 58, in check_python_version
    "Got python {}".format(".".join(python_ver))
TypeError: sequence item 0: expected string, int found
```

**Comment by jflesch** [comment]
This is weird, paperwork-shell has been started with Python 2.7 instead of Python 3.
I'm wondering : was ```python-stdeb``` installed on your system prior to ```python3-stbdev``` ? If so, I think you may have used the Python 2.7 version of pypi-installer instead of the Python 3 version.

**Comment by jflesch** [comment]
Nevermind. It seems python3-stdeb doesn't provide pypi-install (while python-stdeb does, but for python 2.7).
Somehow I installed a version pypi-install for Python 3.

**Comment by jflesch** [comment]
Got it.
I ran ```pip3 install stdeb``` a while ago ...

**Comment by jflesch** [comment]
I've updated again the documentation: 10622efdc30bf967a308674d26081dee92affcfe
(this part of the doc was a contribution. This is why I didn't maintain it correctly)

Thank you for taking the time to report these issues and sorry for the mess.

**Comment by nodiscc** [comment]
Thank you for responding so quickly. I will try the new installation instructions and report back. For your information:

```
$ which pypi-install
/usr/bin/pypi-install

$ dpkg -S /usr/bin/pypi-install
python-stdeb: /usr/bin/pypi-install

$ apt-cache policy python3-pip python-pip python-stdeb
python3-pip:
  Installed: 9.0.1-2
  Candidate: 9.0.1-2
  Version table:
 *** 9.0.1-2 500
        500 http://ftp.fr.debian.org/debian stretch/main amd64 Packages
        500 http://ftp.fr.debian.org/debian stretch/main i386 Packages
        200 http://ftp.fr.debian.org/debian unstable/main amd64 Packages
        200 http://ftp.fr.debian.org/debian unstable/main i386 Packages
        100 /var/lib/dpkg/status
python-pip:
  Installed: 9.0.1-2
  Candidate: 9.0.1-2
  Version table:
 *** 9.0.1-2 500
        500 http://ftp.fr.debian.org/debian stretch/main amd64 Packages
        500 http://ftp.fr.debian.org/debian stretch/main i386 Packages
        200 http://ftp.fr.debian.org/debian unstable/main amd64 Packages
        200 http://ftp.fr.debian.org/debian unstable/main i386 Packages
        100 /var/lib/dpkg/status
python-stdeb:
  Installed: 0.8.5-1
  Candidate: 0.8.5-1
  Version table:
 *** 0.8.5-1 500
        500 http://ftp.fr.debian.org/debian stretch/main amd64 Packages
        500 http://ftp.fr.debian.org/debian stretch/main i386 Packages
        200 http://ftp.fr.debian.org/debian unstable/main amd64 Packages
        200 http://ftp.fr.debian.org/debian unstable/main i386 Packages
        100 /var/lib/dpkg/status
```
