### ISSUE TITLE
Can't execute paperwork on debian/stretch

### ISSUE THREAD

**Issue by fabrice-regnier** [jflesch/paperwork#596]
Hi,

First, congrads for this piece of software ;)

I've installed paperwork this way (https://github.com/jflesch/paperwork/blob/unstable/doc/install.debian.markdown). I  didn't used python-stdeb.

When i run paperwork, it says:
```
fabricer@FR-PORT:~$ paperwork
WARNING paperwork.paperwork            No suitable localization file found.
INFO   pyinsane2.sane.abstract_proc   Starting Pyinsane subprocess
INFO   pyinsane2.sane.abstract_proc   Pyinsane pipes: /tmp/pyinsane_3h12yy0z/pipe_c2s | /tmp/pyinsane_3h12yy0z/pipe_s2c
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.5/dist-packages/pyinsane2/sane/daemon.py", line 159, in <module>
    main_loop(sys.argv[1], sys.argv[2:4])
  File "/usr/local/lib/python3.5/dist-packages/pyinsane2/sane/daemon.py", line 115, in main_loop
    pyinsane.init()
  File "/usr/local/lib/python3.5/dist-packages/pyinsane2/sane/abstract.py", line 45, in init
    sane_init()
  File "/usr/local/lib/python3.5/dist-packages/pyinsane2/sane/rawapi.py", line 525, in sane_init
    assert(sane_available)
AssertionError
```
No screen at all. I need to use kill -9 to kill the process.

I'm not very familiar with python. Where should i start to investigate ?

regards,

f.

**Comment by jflesch** [comment]
You need libsane --> ```apt-get install libsane```

**Comment by fabrice-regnier** [comment]
ahah thank you jflesh! it works like a charm now. Maybe apt-get install libsane should go to the install doc.

regards,

f.

**Comment by jflesch** [comment]
Exactly. This is why I'm going to keep this ticket open. It will serve as a reminder for me to add it in the documentation.

**Comment by jflesch** [comment]
190dda1453e9fa644bbfed86b2fd8b12acedba4e
(on the branch stable too)
